"use client";

import { useMemo, useState } from "react";
import { ArrowRight, CarFront, Check, ChevronDown, GitCompareArrows, Heart, Languages, MapPin, Menu, Search, SlidersHorizontal, Sparkles, X } from "lucide-react";
type Lang = "en" | "fr" | "es";
type Car = { id:number; make:string; model:string; year:number; price:number; km:number; fuel:string; body:string; location:string; image:string; badge:string };
const copy = {
 en:{buy:"Buy",sell:"Sell your car",saved:"Saved",hero:"Find a car that feels right.",sub:"Good cars, clear details, zero pressure.",search:"Search make, model or keyword",go:"Search",filters:"Filters",results:"cars found",sort:"Sort: Recommended",price:"Price",body:"Body type",fuel:"Fuel",year:"Year",any:"Any",reset:"Reset",compare:"Compare",view:"View car",monthly:"est. / month",trusted:"Verified history",quick:"Quick search",popular:"Popular right now",empty:"No cars match those filters.",emptySub:"Try widening your search or resetting the filters.",sellCta:"Ready for your next chapter?",sellSub:"List your car in minutes. We’ll help with the rest.",start:"Start selling"},
 fr:{buy:"Acheter",sell:"Vendre ma voiture",saved:"Favoris",hero:"Trouvez la voiture qui vous ressemble.",sub:"De bonnes voitures, des infos claires, sans pression.",search:"Marque, modèle ou mot-clé",go:"Rechercher",filters:"Filtres",results:"voitures trouvées",sort:"Tri : Recommandées",price:"Prix",body:"Carrosserie",fuel:"Énergie",year:"Année",any:"Tous",reset:"Réinitialiser",compare:"Comparer",view:"Voir la voiture",monthly:"est. / mois",trusted:"Historique vérifié",quick:"Recherche rapide",popular:"Populaires en ce moment",empty:"Aucune voiture ne correspond.",emptySub:"Élargissez votre recherche ou réinitialisez les filtres.",sellCta:"Prêt pour la suite ?",sellSub:"Publiez votre voiture en quelques minutes. On s’occupe du reste.",start:"Commencer"},
 es:{buy:"Comprar",sell:"Vender mi coche",saved:"Guardados",hero:"Encuentra un coche que encaje contigo.",sub:"Buenos coches, datos claros y cero presión.",search:"Marca, modelo o palabra clave",go:"Buscar",filters:"Filtros",results:"coches encontrados",sort:"Orden: Recomendados",price:"Precio",body:"Carrocería",fuel:"Combustible",year:"Año",any:"Cualquiera",reset:"Restablecer",compare:"Comparar",view:"Ver coche",monthly:"est. / mes",trusted:"Historial verificado",quick:"Búsqueda rápida",popular:"Populares ahora",empty:"Ningún coche coincide.",emptySub:"Amplía la búsqueda o restablece los filtros.",sellCta:"¿Listo para tu próxima etapa?",sellSub:"Publica tu coche en minutos. Nosotros te ayudamos con el resto.",start:"Empezar"}
};
const cars:Car[] = [
 {id:1,make:"Volvo",model:"XC40 Recharge",year:2023,price:38900,km:18400,fuel:"Electric",body:"SUV",location:"Lyon",image:"https://images.unsplash.com/photo-1619767886558-efdc259cde1a?auto=format&fit=crop&w=1200&q=85",badge:"Great price"},
 {id:2,make:"BMW",model:"330e M Sport",year:2022,price:35400,km:32100,fuel:"Hybrid",body:"Sedan",location:"Barcelona",image:"https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=1200&q=85",badge:"Just arrived"},
 {id:3,make:"Mercedes-Benz",model:"GLA 200",year:2021,price:31950,km:43700,fuel:"Petrol",body:"SUV",location:"Paris",image:"https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=1200&q=85",badge:"Low mileage"},
 {id:4,make:"Peugeot",model:"e-208 GT",year:2023,price:24800,km:12600,fuel:"Electric",body:"Hatchback",location:"Madrid",image:"https://images.unsplash.com/photo-1609521263047-f8f205293f24?auto=format&fit=crop&w=1200&q=85",badge:"City favorite"},
 {id:5,make:"Audi",model:"A4 Avant",year:2020,price:28750,km:58900,fuel:"Diesel",body:"Wagon",location:"Bordeaux",image:"https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=1200&q=85",badge:"Family pick"},
 {id:6,make:"Tesla",model:"Model 3 Long Range",year:2022,price:32900,km:39100,fuel:"Electric",body:"Sedan",location:"Valencia",image:"https://images.unsplash.com/photo-1560958089-b8a1929cea89?auto=format&fit=crop&w=1200&q=85",badge:"Fast charge"}
];
const money = (n:number, lang:Lang) => new Intl.NumberFormat(lang === "fr" ? "fr-FR" : lang === "es" ? "es-ES" : "en-GB",{style:"currency",currency:"EUR",maximumFractionDigits:0}).format(n);
export default function Home(){
 const [lang,setLang]=useState<Lang>("en"),[query,setQuery]=useState(""),[body,setBody]=useState("Any"),[fuel,setFuel]=useState("Any"),[maxPrice,setMaxPrice]=useState("Any"),[sort,setSort]=useState("recommended");
 const [saved,setSaved]=useState<number[]>([]),[compare,setCompare]=useState<number[]>([]),[mobileFilters,setMobileFilters]=useState(false); const t=copy[lang];
 const filtered=useMemo(()=>{let r=cars.filter(c=>(body==="Any"||c.body===body)&&(fuel==="Any"||c.fuel===fuel)&&(maxPrice==="Any"||c.price<=Number(maxPrice))&&(`${c.make} ${c.model} ${c.location}`.toLowerCase().includes(query.toLowerCase()))); if(sort==="price-low")r=[...r].sort((a,b)=>a.price-b.price); if(sort==="newest")r=[...r].sort((a,b)=>b.year-a.year); if(sort==="mileage")r=[...r].sort((a,b)=>a.km-b.km); return r},[body,fuel,maxPrice,query,sort]);
 const reset=()=>{setQuery("");setBody("Any");setFuel("Any");setMaxPrice("Any")};
 return <main>
  <header className="topbar"><a className="logo" href="#"><span>JF</span>cars<i>.</i></a><nav><a className="active" href="#inventory">{t.buy}</a><a href="#how">How it works</a><a href="#why">Why JFcars</a></nav><div className="actions"><button className="lang"><Languages size={17}/><select aria-label="Language" value={lang} onChange={e=>setLang(e.target.value as Lang)}><option value="en">EN</option><option value="fr">FR</option><option value="es">ES</option></select></button><button className="saved"><Heart size={18}/><span>{t.saved}</span>{saved.length>0&&<b>{saved.length}</b>}</button><button className="sell">{t.sell}<ArrowRight size={17}/></button><button className="menu" aria-label="Menu"><Menu/></button></div></header>
  <section className="hero"><div className="hero-copy"><p className="eyebrow"><Sparkles size={15}/> Used, not second-best.</p><h1>{t.hero}</h1><p>{t.sub}</p><div className="searchbar"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={t.search}/>{query&&<button className="clear" onClick={()=>setQuery("")} aria-label="Clear"><X/></button>}<button className="searchbtn" onClick={()=>document.getElementById("inventory")?.scrollIntoView({behavior:"smooth"})}>{t.go}<ArrowRight/></button></div><div className="quick"><span>{t.quick}:</span>{["Electric","SUV","Under €30k"].map(x=><button key={x} onClick={()=>x==="Electric"?setFuel("Electric"):x==="SUV"?setBody("SUV"):setMaxPrice("30000")}>{x}</button>)}</div></div><div className="hero-art"><img src={cars[0].image} alt="Volvo XC40 in a bright showroom"/><div className="stat"><b>4.9</b><span>buyer rating</span></div><div className="shape shape-one"/><div className="shape shape-two"/></div></section>
  <section className="trust"><span><Check/>7-day returns</span><span><Check/>150-point inspection</span><span><Check/>Simple financing</span><span><Check/>No surprise fees</span></section>
  <section className="market" id="inventory"><aside className={mobileFilters?"filters open":"filters"}><div className="filter-head"><h2>{t.filters}</h2><button onClick={reset}>{t.reset}</button><button className="filter-close" onClick={()=>setMobileFilters(false)}><X/></button></div><Filter title={t.price} value={maxPrice} set={setMaxPrice} values={["Any","25000","30000","35000","40000"]} labels={[t.any,"€25k","€30k","€35k","€40k"]}/><Filter title={t.body} value={body} set={setBody} values={["Any","SUV","Sedan","Hatchback","Wagon"]} labels={[t.any,"SUV","Sedan","Hatchback","Wagon"]}/><Filter title={t.fuel} value={fuel} set={setFuel} values={["Any","Electric","Hybrid","Petrol","Diesel"]} labels={[t.any,"Electric","Hybrid","Petrol","Diesel"]}/><div className="year"><h3>{t.year}</h3><div><span>2020</span><div className="line"><i/><i/></div><span>2024</span></div></div><button className="show-results" onClick={()=>setMobileFilters(false)}>Show {filtered.length} cars</button></aside>
   <div className="inventory"><div className="inventory-head"><div><p>{t.popular}</p><h2>{filtered.length} {t.results}</h2></div><div><button className="mobile-filter" onClick={()=>setMobileFilters(true)}><SlidersHorizontal/> {t.filters}</button><select value={sort} onChange={e=>setSort(e.target.value)} aria-label="Sort cars"><option value="recommended">{t.sort}</option><option value="price-low">Price: Low to high</option><option value="newest">Newest first</option><option value="mileage">Lowest mileage</option></select></div></div>
    {filtered.length?<div className="car-grid">{filtered.map(car=><article className="car-card" key={car.id}><div className="photo"><img src={car.image} alt={`${car.make} ${car.model}`}/><span className="badge">{car.badge}</span><button className={saved.includes(car.id)?"heart on":"heart"} aria-label="Save car" onClick={()=>setSaved(s=>s.includes(car.id)?s.filter(x=>x!==car.id):[...s,car.id])}><Heart fill={saved.includes(car.id)?"currentColor":"none"}/></button></div><div className="card-body"><div className="car-title"><div><p>{car.year} · {car.fuel}</p><h3>{car.make} {car.model}</h3></div><h4>{money(car.price,lang)}</h4></div><div className="meta"><span>{car.km.toLocaleString()} km</span><span>{car.body}</span><span><MapPin/> {car.location}</span></div><div className="verified"><Check/> {t.trusted}<span>{money(Math.round(car.price/72),lang)} {t.monthly}</span></div><div className="card-actions"><button onClick={()=>setCompare(s=>s.includes(car.id)?s.filter(x=>x!==car.id):s.length<3?[...s,car.id]:s)} className={compare.includes(car.id)?"compare selected":"compare"}><GitCompareArrows/>{compare.includes(car.id)?"Added":t.compare}</button><button className="view">{t.view}<ArrowRight/></button></div></div></article>)}</div>:<div className="empty"><CarFront/><h3>{t.empty}</h3><p>{t.emptySub}</p><button onClick={reset}>{t.reset}</button></div>}
   </div></section>
  <section className="sell-band"><div><p>SELL WITH JFCARS</p><h2>{t.sellCta}</h2><span>{t.sellSub}</span></div><button>{t.start}<ArrowRight/></button></section>
  {compare.length>0&&<div className="compare-bar"><div><GitCompareArrows/><span><b>{compare.length}</b> car{compare.length>1?"s":""} selected</span></div><div><button onClick={()=>setCompare([])}>Clear</button><button disabled={compare.length<2}>Compare now <ArrowRight/></button></div></div>}
  <footer><a className="logo" href="#"><span>JF</span>cars<i>.</i></a><p>Move happy. © 2026 JFcars</p><div><a href="#">Help</a><a href="#">Privacy</a><a href="#">Terms</a></div></footer>
 </main>
}
function Filter({title,value,set,values,labels}:{title:string,value:string,set:(v:string)=>void,values:string[],labels:string[]}){return <div className="filter-group"><button className="filter-title"><h3>{title}</h3><ChevronDown/></button><div className="pills">{values.map((v,i)=><button key={v} className={value===v?"active":""} onClick={()=>set(v)}>{labels[i]}</button>)}</div></div>}
