"use client";

import { useMemo, useState } from "react";
import { ArrowRight, CalendarDays, CarFront, Check, ChevronDown, CircleDot, Cog, GitCompareArrows, Heart, KeyRound, Languages, LogOut, MapPin, Menu, Package, Search, Settings, ShoppingBag, ShoppingCart, SlidersHorizontal, Sparkles, User, X } from "lucide-react";
type Lang = "en" | "fr" | "es";
type Car = { id:number; make:string; model:string; year:number; price:number; km:number; fuel:string; body:string; location:string; image:string; badge:string };
const copy = {
 en:{buy:"Buy",sell:"Sell your car",saved:"Saved",hero:"Find a car that feels right.",sub:"Good cars, clear details, zero pressure.",search:"Search make, model or keyword",go:"Search",filters:"Filters",results:"cars found",sort:"Sort: Recommended",price:"Price",body:"Body type",fuel:"Fuel",year:"Year",any:"Any",reset:"Reset",compare:"Compare",view:"View car",monthly:"est. / month",trusted:"Verified history",quick:"Quick search",popular:"Popular right now",empty:"No cars match those filters.",emptySub:"Try widening your search or resetting the filters.",sellCta:"Ready for your next chapter?",sellSub:"List your car in minutes. We’ll help with the rest.",start:"Start selling"},
 fr:{buy:"Acheter",sell:"Vendre ma voiture",saved:"Favoris",hero:"Trouvez la voiture qui vous ressemble.",sub:"De bonnes voitures, des infos claires, sans pression.",search:"Marque, modèle ou mot-clé",go:"Rechercher",filters:"Filtres",results:"voitures trouvées",sort:"Tri : Recommandées",price:"Prix",body:"Carrosserie",fuel:"Énergie",year:"Année",any:"Tous",reset:"Réinitialiser",compare:"Comparer",view:"Voir la voiture",monthly:"est. / mois",trusted:"Historique vérifié",quick:"Recherche rapide",popular:"Populaires en ce moment",empty:"Aucune voiture ne correspond.",emptySub:"Élargissez votre recherche ou réinitialisez les filtres.",sellCta:"Prêt pour la suite ?",sellSub:"Publiez votre voiture en quelques minutes. On s’occupe du reste.",start:"Commencer"},
 es:{buy:"Comprar",sell:"Vender mi coche",saved:"Guardados",hero:"Encuentra un coche que encaje contigo.",sub:"Buenos coches, datos claros y cero presión.",search:"Marca, modelo o palabra clave",go:"Buscar",filters:"Filtros",results:"coches encontrados",sort:"Orden: Recomendados",price:"Precio",body:"Carrocería",fuel:"Combustible",year:"Año",any:"Cualquiera",reset:"Restablecer",compare:"Comparar",view:"Ver coche",monthly:"est. / mes",trusted:"Historial verificado",quick:"Búsqueda rápida",popular:"Populares ahora",empty:"Ningún coche coincide.",emptySub:"Amplía la búsqueda o restablece los filtros.",sellCta:"¿Listo para tu próxima etapa?",sellSub:"Publica tu coche en minutos. Nosotros te ayudamos con el resto.",start:"Empezar"}
};
const cars:Car[] = [
 {id:1,make:"Volvo",model:"XC40 Recharge",year:2023,price:38900,km:18400,fuel:"Electric",body:"SUV",location:"Lyon",image:"https://images.unsplash.com/photo-1619767886558-efdc259cde1a?auto=format&fit=crop&w=1200&q=85",badge:"Great price"},
 {id:2,make:"BMW",model:"330e M Sport",year:2022,price:35400,km:32100,fuel:"Hybrid",body:"Sedan",location:"Barcelona",image:"https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=1200&q=85",badge:"Just arrived"},
 {id:3,make:"Mercedes-Benz",model:"GLA 200",year:2021,price:31950,km:43700,fuel:"Petrol",body:"SUV",location:"Paris",image:"https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=1200&q=85",badge:"Low mileage"},
 {id:4,make:"Peugeot",model:"e-208 GT",year:2023,price:24800,km:12600,fuel:"Electric",body:"Hatchback",location:"Madrid",image:"https://images.unsplash.com/photo-1609521263047-f8f205293f24?auto=format&fit=crop&w=1200&q=85",badge:"City favorite"},
 {id:5,make:"Audi",model:"A4 Avant",year:2020,price:28750,km:58900,fuel:"Diesel",body:"Wagon",location:"Bordeaux",image:"https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=1200&q=85",badge:"Family pick"},
 {id:6,make:"Tesla",model:"Model 3 Long Range",year:2022,price:32900,km:39100,fuel:"Electric",body:"Sedan",location:"Valencia",image:"https://images.unsplash.com/photo-1560958089-b8a1929cea89?auto=format&fit=crop&w=1200&q=85",badge:"Fast charge"}
];
const brands = [
 {name:"Toyota",slug:"toyota",count:84},{name:"BMW",slug:"bmw",count:58},{name:"Mercedes",slug:"mercedes",count:67},{name:"Tesla",slug:"tesla",count:42},{name:"Audi",slug:"audi",count:59},{name:"Volvo",slug:"volvo",count:31},{name:"Peugeot",slug:"peugeot",count:46},{name:"Honda",slug:"honda",count:52}
];
const letters = "ABCDEFGHIJKLMNOPQRSTUVWXYZ".split("");
const money = (n:number, lang:Lang) => new Intl.NumberFormat(lang === "fr" ? "fr-FR" : lang === "es" ? "es-ES" : "en-GB",{style:"currency",currency:"EUR",maximumFractionDigits:0}).format(n);
export default function Home(){
 const [lang,setLang]=useState<Lang>("en"),[query,setQuery]=useState(""),[body,setBody]=useState("Any"),[fuel,setFuel]=useState("Any"),[maxPrice,setMaxPrice]=useState("Any"),[sort,setSort]=useState("recommended");
 const [saved,setSaved]=useState<number[]>([]),[compare,setCompare]=useState<number[]>([]),[cart,setCart]=useState<number[]>([]),[mobileFilters,setMobileFilters]=useState(false),[mode,setMode]=useState<"buy"|"rent"|"parts">("buy"),[brand,setBrand]=useState("All"),[panel,setPanel]=useState<"auth"|"cart"|"profile"|null>(null),[authMode,setAuthMode]=useState<"signin"|"signup">("signin"),[user,setUser]=useState<{name:string,email:string}|null>(null); const t=copy[lang];
 const filtered=useMemo(()=>{let r=cars.filter(c=>(brand==="All"||c.make.toLowerCase().includes(brand.toLowerCase()))&&(body==="Any"||c.body===body)&&(fuel==="Any"||c.fuel===fuel)&&(maxPrice==="Any"||c.price<=Number(maxPrice))&&(`${c.make} ${c.model} ${c.location}`.toLowerCase().includes(query.toLowerCase()))); if(sort==="price-low")r=[...r].sort((a,b)=>a.price-b.price); if(sort==="newest")r=[...r].sort((a,b)=>b.year-a.year); if(sort==="mileage")r=[...r].sort((a,b)=>a.km-b.km); return r},[brand,body,fuel,maxPrice,query,sort]);
 const reset=()=>{setQuery("");setBody("Any");setFuel("Any");setMaxPrice("Any")};
 return <main>
  <header className="topbar"><a className="logo" href="#"><span>JF</span>cars<i>.</i></a><nav><button className={mode==="buy"?"active":""} onClick={()=>setMode("buy")}>Buy a car</button><button className={mode==="rent"?"active":""} onClick={()=>setMode("rent")}>Rent a car</button><button className={mode==="parts"?"active":""} onClick={()=>setMode("parts")}>Car parts</button><a href="#why">Why JFcars</a></nav><div className="actions"><button className="lang"><Languages size={17}/><select aria-label="Language" value={lang} onChange={e=>setLang(e.target.value as Lang)}><option value="en">EN</option><option value="fr">FR</option><option value="es">ES</option></select></button><button className="saved" onClick={()=>setPanel("cart")}><ShoppingCart size={18}/><span>Cart</span>{cart.length>0&&<b>{cart.length}</b>}</button><button className="account" onClick={()=>setPanel(user?"profile":"auth")}><User size={18}/><span>{user?user.name.split(" ")[0]:"Sign in"}</span></button><button className="sell">{t.sell}<ArrowRight size={17}/></button><button className="menu" aria-label="Menu"><Menu/></button></div></header>
  <section className="hero"><div className="hero-copy"><p className="eyebrow"><Sparkles size={15}/> Used, not second-best.</p><h1>{t.hero}</h1><p>{t.sub}</p><div className="searchbar"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={t.search}/>{query&&<button className="clear" onClick={()=>setQuery("")} aria-label="Clear"><X/></button>}<button className="searchbtn" onClick={()=>document.getElementById("inventory")?.scrollIntoView({behavior:"smooth"})}>{t.go}<ArrowRight/></button></div><div className="quick"><span>{t.quick}:</span>{["Electric","SUV","Under €30k"].map(x=><button key={x} onClick={()=>x==="Electric"?setFuel("Electric"):x==="SUV"?setBody("SUV"):setMaxPrice("30000")}>{x}</button>)}</div></div><div className="hero-art"><img src={cars[0].image} alt="Volvo XC40 in a bright showroom"/><div className="stat"><b>4.9</b><span>buyer rating</span></div><div className="shape shape-one"/><div className="shape shape-two"/></div></section>
  <section className="trust"><span><Check/>7-day returns</span><span><Check/>150-point inspection</span><span><Check/>Simple financing</span><span><Check/>No surprise fees</span></section>
  <section className="brand-search" id="inventory"><div className="mode-tabs"><button className={mode==="buy"?"active":""} onClick={()=>setMode("buy")}><CarFront/>Buy</button><button className={mode==="rent"?"active":""} onClick={()=>setMode("rent")}><KeyRound/>Rent</button><button className={mode==="parts"?"active":""} onClick={()=>setMode("parts")}><Cog/>Parts on demand</button></div><div className="brand-strip"><button className={brand==="All"?"active":""} onClick={()=>setBrand("All")}><span className="all-brand">ALL</span><b>All makes</b></button>{brands.slice(0,7).map(b=><button key={b.name} className={brand==b.name?"active":""} onClick={()=>{setBrand(b.name);setMode("buy")}}><img src={`https://cdn.simpleicons.org/${b.slug}/142b3a`} alt=""/><b>{b.name}</b></button>)}</div><div className="quick-filters"><span>Quick refine</span><button onClick={()=>setMaxPrice("30000")}>Under €30k</button><button onClick={()=>setBody("SUV")}>SUV</button><button onClick={()=>setFuel("Electric")}>Electric</button><button onClick={reset}>Clear all</button></div></section>
  {mode==="parts"?<PartsPanel/>:<section className="market"><aside className={mobileFilters?"filters open":"filters"}><div className="directory-title"><h2>Browse makes</h2><span>{brands.reduce((n,b)=>n+b.count,0)} listings</span></div><div className="az-grid">{letters.map(l=><button key={l} disabled={!brands.some(b=>b.name.startsWith(l))}>{l}</button>)}</div><div className="brand-list"><button className={brand==="All"?"active":""} onClick={()=>setBrand("All")}><span>All brands</span><b>{cars.length}</b></button>{brands.map(b=><button key={b.name} className={brand==b.name?"active":""} onClick={()=>setBrand(b.name)}><span>{b.name}</span><b>{b.count}</b></button>)}</div><div className="filter-head"><h2>{t.filters}</h2><button onClick={reset}>{t.reset}</button><button className="filter-close" onClick={()=>setMobileFilters(false)}><X/></button></div><Filter title={t.price} value={maxPrice} set={setMaxPrice} values={["Any","25000","30000","35000","40000"]} labels={[t.any,"€25k","€30k","€35k","€40k"]}/><Filter title={t.body} value={body} set={setBody} values={["Any","SUV","Sedan","Hatchback","Wagon"]} labels={[t.any,"SUV","Sedan","Hatchback","Wagon"]}/><Filter title={t.fuel} value={fuel} set={setFuel} values={["Any","Electric","Hybrid","Petrol","Diesel"]} labels={[t.any,"Electric","Hybrid","Petrol","Diesel"]}/><button className="show-results" onClick={()=>setMobileFilters(false)}>Show {filtered.length} cars</button></aside>
   <div className="inventory"><div className="inventory-head"><div><p>{mode==="rent"?"AVAILABLE TO RENT":t.popular}</p><h2>{filtered.length} {mode==="rent"?"cars ready for your trip":t.results}</h2></div><div><button className="mobile-filter" onClick={()=>setMobileFilters(true)}><SlidersHorizontal/> {t.filters}</button><select value={sort} onChange={e=>setSort(e.target.value)} aria-label="Sort cars"><option value="recommended">{t.sort}</option><option value="price-low">Price: Low to high</option><option value="newest">Newest first</option><option value="mileage">Lowest mileage</option></select></div></div>
    {filtered.length?<div className="car-grid">{filtered.map(car=><article className="car-card" key={car.id}><div className="photo"><img src={car.image} alt={`${car.make} ${car.model}`}/><span className="badge">{mode==="rent"?"Free cancellation":car.badge}</span><button className={saved.includes(car.id)?"heart on":"heart"} aria-label="Save car" onClick={()=>setSaved(s=>s.includes(car.id)?s.filter(x=>x!==car.id):[...s,car.id])}><Heart fill={saved.includes(car.id)?"currentColor":"none"}/></button></div><div className="card-body"><div className="car-title"><div><p>{car.year} · {car.fuel}</p><h3>{car.make} {car.model}</h3></div><h4>{mode==="rent"?`${money(Math.round(car.price/650),lang)}/day`:money(car.price,lang)}</h4></div><div className="meta"><span>{car.km.toLocaleString()} km</span><span>{car.body}</span><span><MapPin/> {car.location}</span></div><div className="verified"><Check/> {mode==="rent"?"Insurance included":t.trusted}<span>{mode==="rent"?"Unlimited options":`${money(Math.round(car.price/72),lang)} ${t.monthly}`}</span></div><div className="card-actions"><button onClick={()=>setCompare(s=>s.includes(car.id)?s.filter(x=>x!==car.id):s.length<3?[...s,car.id]:s)} className={compare.includes(car.id)?"compare selected":"compare"}><GitCompareArrows/>{compare.includes(car.id)?"Added":t.compare}</button><button className={cart.includes(car.id)?"view in-cart":"view"} onClick={()=>setCart(s=>s.includes(car.id)?s:[...s,car.id])}>{cart.includes(car.id)?"In cart":mode==="rent"?"Book now":"Add to cart"}<ShoppingCart/></button></div></div></article>)}</div>:<div className="empty"><CarFront/><h3>{t.empty}</h3><p>{t.emptySub}</p><button onClick={reset}>{t.reset}</button></div>}
   </div></section>}
  <section className="sell-band"><div><p>SELL WITH JFCARS</p><h2>{t.sellCta}</h2><span>{t.sellSub}</span></div><button>{t.start}<ArrowRight/></button></section>
  {compare.length>0&&<div className="compare-bar"><div><GitCompareArrows/><span><b>{compare.length}</b> car{compare.length>1?"s":""} selected</span></div><div><button onClick={()=>setCompare([])}>Clear</button><button disabled={compare.length<2}>Compare now <ArrowRight/></button></div></div>}
  {panel&&<AccountLayer panel={panel} close={()=>setPanel(null)} goAuth={()=>setPanel("auth")} user={user} setUser={setUser} authMode={authMode} setAuthMode={setAuthMode} cart={cart} setCart={setCart} saved={saved} lang={lang}/>}
  <footer><a className="logo" href="#"><span>JF</span>cars<i>.</i></a><p>Move happy. © 2026 JFcars</p><div><a href="#">Help</a><a href="#">Privacy</a><a href="#">Terms</a></div></footer>
 </main>
}
function Filter({title,value,set,values,labels}:{title:string,value:string,set:(v:string)=>void,values:string[],labels:string[]}){return <div className="filter-group"><button className="filter-title"><h3>{title}</h3><ChevronDown/></button><div className="pills">{values.map((v,i)=><button key={v} className={value===v?"active":""} onClick={()=>set(v)}>{labels[i]}</button>)}</div></div>}
function PartsPanel(){return <section className="parts-panel"><div className="parts-intro"><span><Cog/> PARTS ON DEMAND</span><h2>Tell us the part. We’ll find the match.</h2><p>New, used, original or compatible—our verified sellers respond directly to your request.</p><div className="parts-steps"><div><b>1</b><span>Describe your part</span></div><div><b>2</b><span>Get verified offers</span></div><div><b>3</b><span>Choose your match</span></div></div></div><form onSubmit={e=>e.preventDefault()}><label>Vehicle make and model<input placeholder="e.g. 2020 Audi A4"/></label><label>Part needed<input placeholder="e.g. Left LED headlight"/></label><div><label>Part condition<select><option>Any condition</option><option>New</option><option>Used</option><option>Reconditioned</option></select></label><label>Delivery country<select><option>France</option><option>Spain</option><option>Other Europe</option></select></label></div><label>Details<textarea placeholder="Add a part number, VIN, color or anything helpful…"/></label><button>Send my request <ArrowRight/></button><small><CircleDot/> Usually matched within 24 hours</small></form></section>}

function AccountLayer({panel,close,goAuth,user,setUser,authMode,setAuthMode,cart,setCart,saved,lang}:{panel:"auth"|"cart"|"profile",close:()=>void,goAuth:()=>void,user:{name:string,email:string}|null,setUser:(u:{name:string,email:string}|null)=>void,authMode:"signin"|"signup",setAuthMode:(m:"signin"|"signup")=>void,cart:number[],setCart:(v:number[])=>void,saved:number[],lang:Lang}){
 const [profileTab,setProfileTab]=useState("overview");
 const submit=(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const data=new FormData(e.currentTarget);setUser({name:String(data.get("name")||"Alex Morgan"),email:String(data.get("email")||"alex@example.com")});close()};
 const picked=cars.filter(c=>cart.includes(c.id));
 return <div className="layer" onMouseDown={e=>e.target===e.currentTarget&&close()}><section className={`drawer ${panel}`}><button className="drawer-close" onClick={close} aria-label="Close"><X/></button>{panel==="auth"&&<div className="auth-box"><a className="logo" href="#"><span>JF</span>cars<i>.</i></a><p className="auth-kicker">YOUR JFCARS ACCOUNT</p><h2>{authMode==="signin"?"Welcome back.":"Let’s get you moving."}</h2><p>{authMode==="signin"?"Sign in to manage your cars, bookings and requests.":"Create an account to save, compare and move faster."}</p><div className="auth-tabs"><button className={authMode==="signin"?"active":""} onClick={()=>setAuthMode("signin")}>Sign in</button><button className={authMode==="signup"?"active":""} onClick={()=>setAuthMode("signup")}>Create account</button></div><form onSubmit={submit}>{authMode==="signup"&&<label>Full name<input name="name" required placeholder="Alex Morgan"/></label>}<label>Email address<input name="email" type="email" required placeholder="alex@example.com"/></label><label>Password<input name="password" type="password" minLength={6} required placeholder="At least 6 characters"/></label><div className="remember"><label><input type="checkbox"/> Remember me</label><button type="button">Forgot password?</button></div><button className="auth-submit">{authMode==="signin"?"Sign in":"Create my account"}<ArrowRight/></button></form><small>By continuing, you agree to our Terms and Privacy Policy.</small></div>}
 {panel==="cart"&&<div className="cart-box"><p className="auth-kicker">YOUR SELECTION</p><h2>Cart <span>{cart.length}</span></h2>{picked.length?<><div className="cart-items">{picked.map(c=><article key={c.id}><img src={c.image} alt=""/><div><b>{c.make} {c.model}</b><span>{c.year} · {c.km.toLocaleString()} km</span><strong>{money(c.price,lang)}</strong></div><button onClick={()=>setCart(cart.filter(x=>x!==c.id))}><X/></button></article>)}</div><div className="cart-total"><span>Estimated total</span><b>{money(picked.reduce((n,c)=>n+c.price,0),lang)}</b></div><button className="checkout" onClick={()=>user?close():goAuth()}>{user?"Continue to checkout":"Sign in to continue"}<ArrowRight/></button>{!user&&<button className="cart-signin" onClick={()=>{setAuthMode("signup");goAuth()}}>Create an account at checkout</button>}</>:<div className="cart-empty"><ShoppingBag/><h3>Your cart is ready for an adventure.</h3><p>Add a car or rental and it will appear here.</p><button onClick={close}>Keep browsing</button></div>}</div>}
 {panel==="profile"&&user&&<div className="profile-box"><div className="profile-head"><span>{user.name.slice(0,1)}</span><div><p>Welcome back</p><h2>{user.name}</h2><small>{user.email}</small></div></div><nav>{[["overview","Overview",User],["orders","Purchases",Package],["rentals","Rentals",CalendarDays],["settings","Settings",Settings]].map(([id,label,Icon])=><button key={String(id)} className={profileTab===id?"active":""} onClick={()=>setProfileTab(String(id))}><Icon/>{String(label)}</button>)}</nav><div className="profile-content">{profileTab==="overview"&&<><h3>Your JFcars at a glance</h3><div className="profile-stats"><div><Heart/><b>{saved.length}</b><span>Saved cars</span></div><div><ShoppingCart/><b>{cart.length}</b><span>In cart</span></div><div><Cog/><b>1</b><span>Part request</span></div></div><h4>Recent activity</h4><div className="activity"><span><Check/></span><div><b>Profile ready</b><p>Your account is set up and ready to go.</p></div></div></>}{profileTab==="orders"&&<ProfileEmpty icon={Package} title="No purchases yet" text="Your vehicle orders will be tracked here."/>}{profileTab==="rentals"&&<ProfileEmpty icon={CalendarDays} title="No upcoming rentals" text="Book a car and manage your trip here."/>}{profileTab==="settings"&&<><h3>Profile settings</h3><label>Full name<input defaultValue={user.name}/></label><label>Email<input defaultValue={user.email}/></label><button className="save-profile">Save changes</button></>}</div><button className="signout" onClick={()=>{setUser(null);close()}}><LogOut/>Sign out</button></div>}</section></div>
}
function ProfileEmpty({icon:Icon,title,text}:{icon:typeof Package,title:string,text:string}){return <div className="profile-empty"><Icon/><h3>{title}</h3><p>{text}</p></div>}
