import {
  galleryItemLimit,
  galleryStatuses,
  type GalleryStatus,
  normalizeGalleryRecords,
} from '@/lib/storefront-content';
import type {
  Car,
  ContactPreference,
  GalleryItem,
  Lang,
  UserAccount,
} from '@/lib/marketplace/types';

export type {
  AuthSession,
  Car,
  ContactPreference,
  GalleryItem,
  Lang,
  OrderItem,
  OrderRecord,
  PartRequest,
  SellRequest,
  SellerInquiry,
  StorefrontContent,
  StorefrontLocaleContent,
  UserAccount,
} from '@/lib/marketplace/types';
export const VEHICLE_SELLING_ENABLED = false;
export const copy = {
  en: {
    buy: 'Buy',
    sell: 'Sell your car',
    saved: 'Saved',
    hero: 'Find a car that feels right.',
    sub: 'Good cars, clear details, zero pressure.',
    search: 'Search make, model or keyword',
    go: 'Search',
    filters: 'Filters',
    results: 'cars found',
    sort: 'Sort: Recommended',
    price: 'Price',
    body: 'Body type',
    fuel: 'Fuel',
    year: 'Year',
    any: 'Any',
    reset: 'Reset',
    compare: 'Compare',
    view: 'View car',
    monthly: 'est. / month',
    trusted: 'Verified history',
    quick: 'Quick search',
    popular: 'Popular right now',
    empty: 'No cars match those filters.',
    emptySub: 'Try widening your search or resetting the filters.',
    sellCta: 'Ready for your next chapter?',
    sellSub: 'List your car in minutes. We’ll help with the rest.',
    start: 'Start selling',
  },
  fr: {
    buy: 'Acheter',
    sell: 'Vendre ma voiture',
    saved: 'Favoris',
    hero: 'Trouvez la voiture qui vous ressemble.',
    sub: 'De bonnes voitures, des infos claires, sans pression.',
    search: 'Marque, modèle ou mot-clé',
    go: 'Rechercher',
    filters: 'Filtres',
    results: 'voitures trouvées',
    sort: 'Tri : Recommandées',
    price: 'Prix',
    body: 'Carrosserie',
    fuel: 'Énergie',
    year: 'Année',
    any: 'Tous',
    reset: 'Réinitialiser',
    compare: 'Comparer',
    view: 'Voir la voiture',
    monthly: 'est. / mois',
    trusted: 'Historique vérifié',
    quick: 'Recherche rapide',
    popular: 'Populaires en ce moment',
    empty: 'Aucune voiture ne correspond.',
    emptySub: 'Élargissez votre recherche ou réinitialisez les filtres.',
    sellCta: 'Prêt pour la suite ?',
    sellSub: 'Publiez votre voiture en quelques minutes. On s’occupe du reste.',
    start: 'Commencer',
  },
  es: {
    buy: 'Comprar',
    sell: 'Vender mi coche',
    saved: 'Guardados',
    hero: 'Encuentra un coche que encaje contigo.',
    sub: 'Buenos coches, datos claros y cero presión.',
    search: 'Marca, modelo o palabra clave',
    go: 'Buscar',
    filters: 'Filtros',
    results: 'coches encontrados',
    sort: 'Orden: Recomendados',
    price: 'Precio',
    body: 'Carrocería',
    fuel: 'Combustible',
    year: 'Año',
    any: 'Cualquiera',
    reset: 'Restablecer',
    compare: 'Comparar',
    view: 'Ver coche',
    monthly: 'est. / mes',
    trusted: 'Historial verificado',
    quick: 'Búsqueda rápida',
    popular: 'Populares ahora',
    empty: 'Ningún coche coincide.',
    emptySub: 'Amplía la búsqueda o restablece los filtros.',
    sellCta: '¿Listo para tu próxima etapa?',
    sellSub: 'Publica tu coche en minutos. Nosotros te ayudamos con el resto.',
    start: 'Empezar',
  },
};
export const galleryCopy = {
  en: {
    nav: 'Gallery & shipping',
    eyebrow: 'From our team',
    title: 'Real photos. Clear shipping updates.',
    description:
      'Browse the latest photos from our yard and see what is ready, what leaves next and what is already on the road.',
    open: 'Open photo',
    close: 'Close gallery',
    previous: 'Previous gallery photo',
    next: 'Next gallery photo',
    photos: 'photos',
    untitled: 'JFcars gallery photo',
    note: 'Team update',
    location: 'Location',
    date: 'Updated',
    departure: 'Left on',
    eta: 'Estimated arrival',
    reference: 'Shipment / batch',
    process: 'Shipment update categories',
    empty: 'No photo update has been posted for this stage yet.',
    loadMore: 'Show more photos',
    sections: {
      all: 'Photo gallery',
      ready_to_ship: 'Ready to ship',
      preparing: 'Next shipment',
      in_transit: 'On the road',
    },
    statuses: {
      ready_to_load: 'Preparing to load',
      loaded: 'Loading complete',
      ready_to_ship: 'Ready to ship',
      shipped_out: 'Shipped out',
      in_transit: 'In transit',
      arrived_unloaded: 'Arrived & unloaded',
      in_store: 'In local stock',
    },
  },
  fr: {
    nav: 'Galerie et expéditions',
    eyebrow: 'Notre équipe sur le terrain',
    title: 'De vraies photos. Des nouvelles claires.',
    description:
      'Parcourez les dernières photos de notre parc et voyez ce qui est prêt, ce qui part prochainement et ce qui est déjà en route.',
    open: 'Ouvrir la photo',
    close: 'Fermer la galerie',
    previous: 'Photo précédente de la galerie',
    next: 'Photo suivante de la galerie',
    photos: 'photos',
    untitled: 'Photo de la galerie JFcars',
    note: 'Note de l’équipe',
    location: 'Lieu',
    date: 'Mise à jour',
    departure: 'Date de départ',
    eta: 'Arrivée estimée',
    reference: 'Expédition / lot',
    process: 'Rubriques de suivi des expéditions',
    empty: 'Aucune mise à jour photo n’a encore été publiée pour cette étape.',
    loadMore: 'Afficher plus de photos',
    sections: {
      all: 'Galerie photos',
      ready_to_ship: 'Prêt à expédier',
      preparing: 'Prochaine expédition',
      in_transit: 'Déjà en route',
    },
    statuses: {
      ready_to_load: 'Préparation du chargement',
      loaded: 'Chargement terminé',
      ready_to_ship: 'Prêt à expédier',
      shipped_out: 'Expédié',
      in_transit: 'Expédié / en transit',
      arrived_unloaded: 'Arrivé et déchargé',
      in_store: 'En stock local',
    },
  },
  es: {
    nav: 'Galería y envíos',
    eyebrow: 'De parte de nuestro equipo',
    title: 'Fotos reales. Envíos claros.',
    description:
      'Mira las últimas fotos de nuestro depósito y descubre qué está listo, qué sale próximamente y qué ya está en camino.',
    open: 'Abrir foto',
    close: 'Cerrar galería',
    previous: 'Foto anterior de la galería',
    next: 'Foto siguiente de la galería',
    photos: 'fotos',
    untitled: 'Foto de la galería JFcars',
    note: 'Nota del equipo',
    location: 'Ubicación',
    date: 'Fecha',
    departure: 'Fecha de salida',
    eta: 'Llegada estimada',
    reference: 'Envío / lote',
    process: 'Categorías de seguimiento de envíos',
    empty:
      'Todavía no se ha publicado ninguna actualización con fotos para esta etapa.',
    loadMore: 'Mostrar más fotos',
    sections: {
      all: 'Galería de fotos',
      ready_to_ship: 'Listo para enviar',
      preparing: 'Próximo envío',
      in_transit: 'Ya en camino',
    },
    statuses: {
      ready_to_load: 'Preparando la carga',
      loaded: 'Carga terminada',
      ready_to_ship: 'Listo para enviar',
      shipped_out: 'Enviado',
      in_transit: 'Enviado / en tránsito',
      arrived_unloaded: 'Llegado y descargado',
      in_store: 'En stock local',
    },
  },
} as const;

export type GallerySection =
  | 'all'
  | 'preparing'
  | 'ready_to_ship'
  | 'in_transit';

export const gallerySections: {
  id: GallerySection;
  statuses: readonly GalleryStatus[];
}[] = [
  { id: 'all', statuses: galleryStatuses },
  { id: 'ready_to_ship', statuses: ['ready_to_ship', 'in_store'] },
  { id: 'preparing', statuses: ['ready_to_load', 'loaded'] },
  { id: 'in_transit', statuses: ['shipped_out', 'in_transit'] },
];

export const defaultHeroVideo =
  'https://videos.pexels.com/video-files/37074025/15705634_2160_3840_30fps.mp4';
export const coreGalleryItems: GalleryItem[] = [
  {
    id: 'shipment-loading',
    image: '/jfcars-gallery-loading.webp',
    captions: {
      en: 'Vehicles secured for shipment',
      fr: 'Véhicules sécurisés pour l’expédition',
      es: 'Vehículos asegurados para el envío',
    },
    comments: {
      en: 'Vehicles are checked, photographed and lined up before container loading. The team posts a new note when loading is complete.',
      fr: 'Les véhicules sont contrôlés, photographiés et alignés avant le chargement du conteneur. L’équipe publie une nouvelle note une fois le chargement terminé.',
      es: 'Los vehículos se revisan, fotografían y preparan antes de cargarlos en el contenedor. El equipo publica una nueva nota al terminar la carga.',
    },
    status: 'ready_to_load',
    date: '',
    location: 'Europe',
    reference: 'JF-LOAD',
  },
  {
    id: 'shipment-unloading',
    image: '/jfcars-gallery-unloading.webp',
    captions: {
      en: 'Careful unloading on arrival',
      fr: 'Déchargement soigné à l’arrivée',
      es: 'Descarga cuidadosa a la llegada',
    },
    comments: {
      en: 'Arrival photos document unloading and the handover to our regional operations team.',
      fr: 'Les photos d’arrivée documentent le déchargement et la remise à notre équipe régionale.',
      es: 'Las fotos de llegada documentan la descarga y la entrega a nuestro equipo regional.',
    },
    status: 'arrived_unloaded',
    date: '',
    location: 'Pointe-Noire',
    reference: 'JF-ARRIVAL',
  },
  {
    id: 'shipment-on-the-road',
    image: '/jfcars-central-africa-hero.webp',
    captions: {
      en: 'Vehicle delivery underway',
      fr: 'Livraison du véhicule en cours',
      es: 'Entrega del vehículo en curso',
    },
    comments: {
      en: 'This vehicle has left our yard. We will add the arrival photos here as soon as the local team receives it.',
      fr: 'Ce véhicule a quitté notre parc. Nous ajouterons ici les photos d’arrivée dès sa réception par l’équipe locale.',
      es: 'Este vehículo ya salió de nuestro depósito. Añadiremos aquí las fotos de llegada en cuanto lo reciba el equipo local.',
    },
    status: 'in_transit',
    date: '',
    location: 'On the road',
    reference: 'JF-TRANSIT',
  },
  {
    id: 'local-parts-store',
    image: '/jfcars-gallery-parts-store.webp',
    captions: {
      en: 'Parts available in our local store',
      fr: 'Pièces disponibles dans notre magasin local',
      es: 'Repuestos disponibles en nuestra tienda local',
    },
    comments: {
      en: 'Parts held locally are photographed with a short availability and condition note.',
      fr: 'Les pièces disponibles localement sont photographiées avec une courte note sur leur disponibilité et leur état.',
      es: 'Los repuestos disponibles localmente se fotografían con una breve nota sobre su disponibilidad y estado.',
    },
    status: 'in_store',
    date: '',
    location: 'JFcars Store',
    reference: 'JF-STOCK',
  },
];
export const demoShipments: Array<{
  id: string;
  reference: string;
  status: GalleryStatus;
  location: string;
  departureDate?: string;
  eta?: string;
  captions: GalleryItem['captions'];
  comments: GalleryItem['comments'];
  images: string[];
}> = [
  {
    id: 'next-september',
    reference: 'JF-NEXT-0926',
    status: 'ready_to_load',
    location: 'Antwerp, Belgium',
    captions: {
      en: 'Next shipment being prepared',
      fr: 'Prochaine expédition en préparation',
      es: 'Próximo envío en preparación',
    },
    comments: {
      en: 'Vehicles have passed the first inspection and are being photographed before loading.',
      fr: 'Les véhicules ont passé le premier contrôle et sont photographiés avant le chargement.',
      es: 'Los vehículos pasaron la primera inspección y se están fotografiando antes de la carga.',
    },
    images: [
      'https://images.unsplash.com/photo-1619767886558-efdc259cde1a?auto=format&fit=crop&w=1400&q=85',
      'https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=1400&q=85',
      'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1400&q=85',
      'https://images.unsplash.com/photo-1494905998402-395d579af36f?auto=format&fit=crop&w=1400&q=85',
    ],
  },
  {
    id: 'ready-october',
    reference: 'JF-READY-1026',
    status: 'ready_to_ship',
    location: 'Port of Antwerp',
    departureDate: '2026-09-22',
    eta: '2026-10-18',
    captions: {
      en: 'Ready for the October sailing',
      fr: 'Prêt pour le départ d’octobre',
      es: 'Listo para la salida de octubre',
    },
    comments: {
      en: 'The vehicle set is complete, documented and waiting for its confirmed vessel.',
      fr: 'Le lot de véhicules est complet, documenté et attend son navire confirmé.',
      es: 'El lote de vehículos está completo, documentado y espera su buque confirmado.',
    },
    images: [
      'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=1400&q=85',
      'https://images.unsplash.com/photo-1503736334956-4c8f8e92946d?auto=format&fit=crop&w=1400&q=85',
      'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=1400&q=85',
      'https://images.unsplash.com/photo-1609521263047-f8f205293f24?auto=format&fit=crop&w=1400&q=85',
    ],
  },
  {
    id: 'road-september',
    reference: 'JF-ROAD-0910',
    status: 'in_transit',
    location: 'Atlantic route · Pointe-Noire',
    departureDate: '2026-09-10',
    eta: '2026-10-02',
    captions: {
      en: 'September shipment on the road',
      fr: 'Expédition de septembre en route',
      es: 'Envío de septiembre en camino',
    },
    comments: {
      en: 'This shipment has departed. The next update will be posted after the port arrival check.',
      fr: 'Cette expédition est partie. La prochaine mise à jour sera publiée après le contrôle à l’arrivée au port.',
      es: 'Este envío ya salió. La próxima actualización se publicará después del control de llegada al puerto.',
    },
    images: [
      'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=1400&q=85',
      'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&w=1400&q=85',
      'https://images.unsplash.com/photo-1560958089-b8a1929cea89?auto=format&fit=crop&w=1400&q=85',
      'https://images.unsplash.com/photo-1549924231-f129b911e442?auto=format&fit=crop&w=1400&q=85',
    ],
  },
  {
    id: 'next-suv-batch',
    reference: 'JF-NEXT-SUV-03',
    status: 'ready_to_load',
    location: 'Rotterdam, Netherlands',
    captions: {
      en: 'SUV batch awaiting inspection',
      fr: 'Lot de SUV en attente de contrôle',
      es: 'Lote de SUV pendiente de inspección',
    },
    comments: {
      en: 'A second group is being checked and documented before its loading slot.',
      fr: 'Un deuxième lot est contrôlé et documenté avant son créneau de chargement.',
      es: 'Un segundo lote está siendo revisado y documentado antes de su turno de carga.',
    },
    images: [
      'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1400&q=85',
      'https://images.unsplash.com/photo-1551830820-330a71b99659?auto=format&fit=crop&w=1400&q=85',
    ],
  },
  {
    id: 'next-city-cars',
    reference: 'JF-NEXT-CITY-07',
    status: 'loaded',
    location: 'Le Havre, France',
    captions: {
      en: 'City cars loaded for the next departure',
      fr: 'Citadines chargées pour le prochain départ',
      es: 'Coches urbanos cargados para la próxima salida',
    },
    comments: {
      en: 'Loading is complete. Final shipping documents are now being prepared.',
      fr: 'Le chargement est terminé. Les derniers documents d’expédition sont en préparation.',
      es: 'La carga ha terminado. Se están preparando los últimos documentos de envío.',
    },
    images: [
      'https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?auto=format&fit=crop&w=1400&q=85',
      'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&w=1400&q=85',
    ],
  },
  {
    id: 'ready-family-cars',
    reference: 'JF-READY-FAM-12',
    status: 'ready_to_ship',
    location: 'Port of Rotterdam',
    departureDate: '2026-09-26',
    eta: '2026-10-21',
    captions: {
      en: 'Family vehicles ready to ship',
      fr: 'Véhicules familiaux prêts à expédier',
      es: 'Vehículos familiares listos para enviar',
    },
    comments: {
      en: 'Inspection, photos and export paperwork are complete for this batch.',
      fr: 'Le contrôle, les photos et les documents d’exportation de ce lot sont terminés.',
      es: 'La inspección, las fotos y la documentación de exportación de este lote están completas.',
    },
    images: [
      'https://images.unsplash.com/photo-1550355291-bbee04a92027?auto=format&fit=crop&w=1400&q=85',
      'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&w=1400&q=85',
    ],
  },
  {
    id: 'ready-pickups',
    reference: 'JF-READY-PU-04',
    status: 'ready_to_ship',
    location: 'Antwerp vehicle terminal',
    departureDate: '2026-09-29',
    eta: '2026-10-25',
    captions: {
      en: 'Pickup vehicles cleared for departure',
      fr: 'Pick-up autorisés au départ',
      es: 'Pick-ups autorizados para la salida',
    },
    comments: {
      en: 'This group has been cleared and is waiting in the secure export area.',
      fr: 'Ce groupe a été autorisé et attend dans la zone d’exportation sécurisée.',
      es: 'Este grupo ha sido autorizado y espera en la zona segura de exportación.',
    },
    images: [
      'https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?auto=format&fit=crop&w=1400&q=85',
      'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=1400&q=85',
    ],
  },
  {
    id: 'road-pointe-noire',
    reference: 'JF-ROAD-PNR-08',
    status: 'shipped_out',
    location: 'Atlantic Ocean · Pointe-Noire',
    departureDate: '2026-09-08',
    eta: '2026-09-30',
    captions: {
      en: 'Pointe-Noire shipment departed',
      fr: 'Expédition pour Pointe-Noire partie',
      es: 'Envío a Pointe-Noire en ruta',
    },
    comments: {
      en: 'The vessel has departed and the shipment is progressing on schedule.',
      fr: 'Le navire est parti et l’expédition avance selon le calendrier prévu.',
      es: 'El buque ha partido y el envío avanza según lo previsto.',
    },
    images: [
      'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=1400&q=85',
      'https://images.unsplash.com/photo-1609521263047-f8f205293f24?auto=format&fit=crop&w=1400&q=85',
    ],
  },
  {
    id: 'road-douala',
    reference: 'JF-ROAD-DLA-05',
    status: 'in_transit',
    location: 'Atlantic Ocean · Douala',
    departureDate: '2026-09-12',
    eta: '2026-10-07',
    captions: {
      en: 'Douala shipment in transit',
      fr: 'Expédition pour Douala en transit',
      es: 'Envío a Douala en tránsito',
    },
    comments: {
      en: 'The carrier has confirmed departure. Port arrival details will follow.',
      fr: 'Le transporteur a confirmé le départ. Les détails d’arrivée au port suivront.',
      es: 'El transportista confirmó la salida. Próximamente se publicarán los datos de llegada.',
    },
    images: [
      'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=1400&q=85',
      'https://images.unsplash.com/photo-1560958089-b8a1929cea89?auto=format&fit=crop&w=1400&q=85',
    ],
  },
];
export const demoGalleryItems: GalleryItem[] = demoShipments.flatMap(
  (shipment) =>
    shipment.images.map((image, index) => ({
      id: `${shipment.id}-${index + 1}`,
      image,
      captions: shipment.captions,
      comments: shipment.comments,
      status: shipment.status,
      date: '2026-09-15',
      departureDate: shipment.departureDate,
      eta: shipment.eta,
      location: shipment.location,
      reference: shipment.reference,
    })),
);
export const defaultGalleryItems: GalleryItem[] = [
  ...coreGalleryItems,
  ...demoGalleryItems,
];
export const normalizeGallery = (items: GalleryItem[] | undefined) => {
  const valid = normalizeGalleryRecords(items, galleryItemLimit).map((item) => {
    const fallback = defaultGalleryItems.find((entry) => entry.id === item.id);
    return {
      ...fallback,
      ...item,
      captions: { ...fallback?.captions, ...item.captions },
      comments: { ...fallback?.comments, ...item.comments },
      location: item.location || fallback?.location || '',
      reference: item.reference || fallback?.reference || '',
      status: item.status || fallback?.status || 'ready_to_load',
    };
  });
  if (!valid.length) return defaultGalleryItems;
  const hasOnlyOriginalSamples = valid.every((item) =>
    coreGalleryItems.some((sample) => sample.id === item.id),
  );
  return hasOnlyOriginalSamples ? [...valid, ...demoGalleryItems] : valid;
};
export const galleryExtras = [
  'https://images.unsplash.com/photo-1550355291-bbee04a92027?auto=format&fit=crop&w=1200&q=85',
  'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&w=1200&q=85',
];
export const seedMarketMeta: Record<
  number,
  Pick<
    Car,
    | 'origin'
    | 'country'
    | 'city'
    | 'importRegion'
    | 'location'
    | 'engineLitres'
    | 'sellerType'
    | 'verified'
    | 'available'
    | 'listedDaysAgo'
    | 'rentable'
    | 'dailyRate'
  >
> = {
  1: {
    origin: 'local',
    country: 'Republic of the Congo',
    city: 'Brazzaville',
    location: 'Brazzaville',
    engineLitres: 0,
    sellerType: 'Dealer',
    verified: true,
    available: true,
    listedDaysAgo: 3,
    rentable: true,
    dailyRate: 45_000,
  },
  2: {
    origin: 'local',
    country: 'Republic of the Congo',
    city: 'Pointe-Noire',
    location: 'Pointe-Noire',
    engineLitres: 2,
    sellerType: 'Dealer',
    verified: true,
    available: true,
    listedDaysAgo: 1,
    rentable: true,
    dailyRate: 55_000,
  },
  3: {
    origin: 'abroad',
    importRegion: 'Europe',
    location: 'Europe',
    engineLitres: 4,
    sellerType: 'Dealer',
    verified: false,
    available: true,
    listedDaysAgo: 4,
    rentable: false,
  },
  4: {
    origin: 'local',
    country: 'Cameroon',
    city: 'Douala',
    location: 'Douala',
    engineLitres: 0,
    sellerType: 'Dealer',
    verified: true,
    available: true,
    listedDaysAgo: 2,
    rentable: true,
    dailyRate: 35_000,
  },
  5: {
    origin: 'local',
    country: 'Gabon',
    city: 'Libreville',
    location: 'Libreville',
    engineLitres: 2,
    sellerType: 'Private',
    verified: false,
    available: true,
    listedDaysAgo: 6,
    rentable: false,
  },
  6: {
    origin: 'abroad',
    importRegion: 'America',
    location: 'America',
    engineLitres: 0,
    sellerType: 'Dealer',
    verified: true,
    available: true,
    listedDaysAgo: 5,
    rentable: false,
  },
  7: {
    origin: 'local',
    country: 'Angola',
    city: 'Cabinda',
    location: 'Cabinda',
    engineLitres: 2.8,
    sellerType: 'Dealer',
    verified: true,
    available: true,
    listedDaysAgo: 1,
    rentable: true,
    dailyRate: 50_000,
  },
  8: {
    origin: 'local',
    country: 'DR Congo',
    city: 'Kinshasa',
    location: 'Kinshasa',
    engineLitres: 1.5,
    sellerType: 'Dealer',
    verified: true,
    available: true,
    listedDaysAgo: 7,
    rentable: true,
    dailyRate: 42_000,
  },
};
export const cars: Car[] = [
  {
    id: 1,
    make: 'Volvo',
    model: 'XC40 Recharge',
    year: 2023,
    price: 25500000,
    km: 18400,
    fuel: 'Electric',
    body: 'SUV',
    location: 'Brazzaville',
    color: 'Sage',
    transmission: 'Automatic',
    drivetrain: 'AWD',
    doors: 5,
    seats: 5,
    image:
      'https://images.unsplash.com/photo-1619767886558-efdc259cde1a?auto=format&fit=crop&w=1200&q=85',
    images: [
      'https://images.unsplash.com/photo-1619767886558-efdc259cde1a?auto=format&fit=crop&w=1400&q=85',
      ...galleryExtras,
    ],
    badge: 'Great price',
  },
  {
    id: 2,
    make: 'BMW',
    model: '330e M Sport',
    year: 2022,
    price: 23200000,
    km: 32100,
    fuel: 'Hybrid',
    body: 'Sedan',
    location: 'Pointe-Noire',
    color: 'Blue',
    transmission: 'Automatic',
    drivetrain: 'RWD',
    doors: 4,
    seats: 5,
    image:
      'https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=1200&q=85',
    images: [
      'https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=1400&q=85',
      'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1494905998402-395d579af36f?auto=format&fit=crop&w=1200&q=85',
    ],
    badge: 'Just arrived',
  },
  {
    id: 3,
    make: 'Mercedes-Benz',
    model: 'AMG GT',
    year: 2021,
    price: 20900000,
    km: 43700,
    fuel: 'Petrol',
    body: 'Coupe',
    location: 'Cabinda',
    color: 'Silver',
    transmission: 'Automatic',
    drivetrain: 'RWD',
    doors: 2,
    seats: 2,
    image:
      'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=1200&q=85',
    images: [
      'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=1400&q=85',
      'https://images.unsplash.com/photo-1503736334956-4c8f8e92946d?auto=format&fit=crop&w=1200&q=85',
      'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=1200&q=85',
    ],
    badge: 'Low mileage',
  },
  {
    id: 4,
    make: 'Peugeot',
    model: 'e-208 GT',
    year: 2023,
    price: 16200000,
    km: 12600,
    fuel: 'Electric',
    body: 'Hatchback',
    location: 'Douala',
    color: 'Yellow',
    transmission: 'Automatic',
    drivetrain: 'FWD',
    doors: 5,
    seats: 5,
    image:
      'https://images.unsplash.com/photo-1609521263047-f8f205293f24?auto=format&fit=crop&w=1200&q=85',
    images: [
      'https://images.unsplash.com/photo-1609521263047-f8f205293f24?auto=format&fit=crop&w=1400&q=85',
      'https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?auto=format&fit=crop&w=1200&q=85',
      ...galleryExtras.slice(0, 1),
    ],
    badge: 'City favorite',
  },
  {
    id: 5,
    make: 'Audi',
    model: 'A4 Avant',
    year: 2020,
    price: 18800000,
    km: 58900,
    fuel: 'Diesel',
    body: 'Wagon',
    location: 'Libreville',
    color: 'Black',
    transmission: 'Automatic',
    drivetrain: 'AWD',
    doors: 5,
    seats: 5,
    image:
      'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=1200&q=85',
    images: [
      'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=1400&q=85',
      'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&w=1200&q=85',
      ...galleryExtras.slice(1),
    ],
    badge: 'Family pick',
  },
  {
    id: 6,
    make: 'Tesla',
    model: 'Model 3 Long Range',
    year: 2022,
    price: 21600000,
    km: 39100,
    fuel: 'Electric',
    body: 'Sedan',
    location: 'Kinshasa',
    color: 'White',
    transmission: 'Automatic',
    drivetrain: 'AWD',
    doors: 4,
    seats: 5,
    image:
      'https://images.unsplash.com/photo-1560958089-b8a1929cea89?auto=format&fit=crop&w=1200&q=85',
    images: [
      'https://images.unsplash.com/photo-1560958089-b8a1929cea89?auto=format&fit=crop&w=1400&q=85',
      'https://images.unsplash.com/photo-1549924231-f129b911e442?auto=format&fit=crop&w=1200&q=85',
      ...galleryExtras.slice(0, 1),
    ],
    badge: 'Fast charge',
  },
  {
    id: 7,
    make: 'Toyota',
    model: 'Hilux 2.8 D-4D',
    year: 2021,
    price: 19800000,
    km: 68400,
    fuel: 'Diesel',
    body: 'Pickup',
    location: 'Brazzaville',
    color: 'White',
    transmission: 'Manual',
    drivetrain: 'AWD',
    doors: 4,
    seats: 5,
    image:
      'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1200&q=85',
    images: [
      'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1400&q=85',
      'https://images.unsplash.com/photo-1551830820-330a71b99659?auto=format&fit=crop&w=1200&q=85',
      ...galleryExtras.slice(0, 1),
    ],
    badge: 'New listing',
  },
  {
    id: 8,
    make: 'Honda',
    model: 'CR-V Executive',
    year: 2020,
    price: 17400000,
    km: 52600,
    fuel: 'Petrol',
    body: 'SUV',
    location: 'Libreville',
    color: 'Black',
    transmission: 'Automatic',
    drivetrain: 'AWD',
    doors: 5,
    seats: 5,
    image:
      'https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?auto=format&fit=crop&w=1200&q=85',
    images: [
      'https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?auto=format&fit=crop&w=1400&q=85',
      'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&w=1200&q=85',
      ...galleryExtras.slice(1),
    ],
    badge: 'Family pick',
  },
].map((car) => ({ ...car, sample: true, ...seedMarketMeta[car.id] }));
export const brands = [
  { name: 'Toyota', slug: 'toyota', count: 84 },
  { name: 'BMW', slug: 'bmw', count: 58 },
  { name: 'Mercedes', slug: 'mercedes', count: 67 },
  { name: 'Tesla', slug: 'tesla', count: 42 },
  { name: 'Audi', slug: 'audi', count: 59 },
  { name: 'Volvo', slug: 'volvo', count: 31 },
  { name: 'Peugeot', slug: 'peugeot', count: 46 },
  { name: 'Honda', slug: 'honda', count: 52 },
];
export const canonicalBrandName = (make: string) =>
  make.toLowerCase().startsWith('mercedes') ? 'Mercedes' : make;
export const catalogBrands = (inventory: Car[]) => {
  const totals = new Map<string, number>();
  inventory
    .filter((car) => !car.hidden)
    .forEach((car) => {
      const name = canonicalBrandName(car.make);
      totals.set(name, (totals.get(name) || 0) + 1);
    });
  return Array.from(totals, ([name, count]) => ({
    name,
    count,
    slug:
      brands.find((brand) => brand.name === name)?.slug ||
      name.toLowerCase().replace(/[^a-z0-9]+/g, '-'),
  })).sort((a, b) => a.name.localeCompare(b.name));
};
export const letters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('');
export const money = (n: number, lang: Lang) =>
  `${new Intl.NumberFormat(lang === 'fr' ? 'fr-FR' : lang === 'es' ? 'es-ES' : 'en-US', { maximumFractionDigits: 0 }).format(n)} FCFA`;
export const rentalRate = (car: Car) =>
  Math.max(0, Math.round(car.dailyRate || 0));
export const rentalDaysBetween = (start: string, end: string) => {
  const startTime = Date.parse(`${start}T00:00:00Z`);
  const endTime = Date.parse(`${end}T00:00:00Z`);
  if (!Number.isFinite(startTime) || !Number.isFinite(endTime)) return 0;
  return Math.ceil((endTime - startTime) / 86_400_000);
};
export const vocabulary: Record<Lang, Record<string, string>> = {
  en: {},
  fr: {
    Electric: 'Électrique',
    Hybrid: 'Hybride',
    Petrol: 'Essence',
    Diesel: 'Diesel',
    Sedan: 'Berline',
    Hatchback: 'Citadine',
    Wagon: 'Break',
    Coupe: 'Coupé',
    Pickup: 'Pick-up',
    Van: 'Fourgon',
    Automatic: 'Automatique',
    Manual: 'Manuelle',
    Black: 'Noir',
    White: 'Blanc',
    Silver: 'Argent',
    Blue: 'Bleu',
    Yellow: 'Jaune',
    Sage: 'Vert sauge',
    'Great price': 'Très bon prix',
    'Just arrived': 'Nouvel arrivage',
    'Low mileage': 'Faible kilométrage',
    'City favorite': 'Favori en ville',
    'Family pick': 'Choix famille',
    'Fast charge': 'Recharge rapide',
    'New listing': 'Nouvelle annonce',
    Local: 'Local',
    Abroad: 'À l’étranger',
    Europe: 'Europe',
    Asia: 'Asie',
    America: 'Amérique',
    'Republic of the Congo': 'République du Congo',
    Cameroon: 'Cameroun',
    Gabon: 'Gabon',
    Angola: 'Angola',
    'DR Congo': 'RD Congo',
    Dealer: 'Professionnel',
    Private: 'Particulier',
  },
  es: {
    Electric: 'Eléctrico',
    Hybrid: 'Híbrido',
    Petrol: 'Gasolina',
    Diesel: 'Diésel',
    Sedan: 'Sedán',
    Hatchback: 'Compacto',
    Wagon: 'Familiar',
    Coupe: 'Cupé',
    Pickup: 'Pick-up',
    Van: 'Furgoneta',
    Automatic: 'Automático',
    Manual: 'Manual',
    Black: 'Negro',
    White: 'Blanco',
    Silver: 'Plata',
    Blue: 'Azul',
    Yellow: 'Amarillo',
    Sage: 'Verde salvia',
    'Great price': 'Excelente precio',
    'Just arrived': 'Recién llegado',
    'Low mileage': 'Poco kilometraje',
    'City favorite': 'Favorito urbano',
    'Family pick': 'Ideal para familias',
    'Fast charge': 'Carga rápida',
    'New listing': 'Anuncio nuevo',
    Local: 'Local',
    Abroad: 'En el extranjero',
    Europe: 'Europa',
    Asia: 'Asia',
    America: 'América',
    'Republic of the Congo': 'República del Congo',
    Cameroon: 'Camerún',
    Gabon: 'Gabón',
    Angola: 'Angola',
    'DR Congo': 'RD del Congo',
    Dealer: 'Profesional',
    Private: 'Particular',
  },
};
export const localize = (value: string | undefined, lang: Lang) =>
  value ? vocabulary[lang][value] || value : '—';
export const localeFor = (lang: Lang) =>
  lang === 'fr' ? 'fr-FR' : lang === 'es' ? 'es-ES' : 'en-US';
export const numberFor = (value: number, lang: Lang) =>
  new Intl.NumberFormat(localeFor(lang)).format(value);
export const carPlace = (car: Car, lang: Lang) =>
  car.origin === 'abroad'
    ? localize(car.importRegion || car.location, lang)
    : [localize(car.country, lang), car.city || car.location]
        .filter((value) => value && value !== '—')
        .join(' · ');
export const citiesByCountry: Record<string, string[]> = {
  'Republic of the Congo': ['Brazzaville', 'Pointe-Noire'],
  Angola: ['Cabinda'],
  Cameroon: ['Douala'],
  Gabon: ['Libreville'],
  'DR Congo': ['Kinshasa'],
};
export const accountMarkets = Object.keys(citiesByCountry);
export const contactPreferenceLabels: Record<
  Lang,
  Record<ContactPreference, string>
> = {
  en: { WhatsApp: 'WhatsApp', Phone: 'Phone call', Email: 'Email' },
  fr: { WhatsApp: 'WhatsApp', Phone: 'Appel téléphonique', Email: 'E-mail' },
  es: { WhatsApp: 'WhatsApp', Phone: 'Llamada telefónica', Email: 'Correo' },
};
export const languageLabels: Record<Lang, Record<Lang, string>> = {
  en: { en: 'English', fr: 'French', es: 'Spanish' },
  fr: { en: 'Anglais', fr: 'Français', es: 'Espagnol' },
  es: { en: 'Inglés', fr: 'Francés', es: 'Español' },
};
export const profileCompletion = (user: UserAccount | null) => {
  if (!user) return 0;
  const fields = [
    user.name,
    user.email,
    user.phone,
    user.country,
    user.city,
    user.preferredContact,
    user.preferredLanguage,
  ];
  return Math.round(
    (fields.filter((value) => String(value || '').trim()).length /
      fields.length) *
      100,
  );
};
export const countryForCity = (city: string) =>
  Object.entries(citiesByCountry).find(([, cities]) =>
    cities.includes(city),
  )?.[0];
export const orderStatus = (status: string, lang: Lang) => {
  const statuses: Record<Lang, Record<string, string>> = {
    en: {
      New: 'New request',
      Contacted: 'Contacted',
      Complete: 'Complete',
      Cancelled: 'Cancelled',
    },
    fr: {
      New: 'Nouvelle demande',
      Contacted: 'Contacté',
      Complete: 'Terminée',
      Cancelled: 'Annulée',
    },
    es: {
      New: 'Nueva solicitud',
      Contacted: 'Contactado',
      Complete: 'Completada',
      Cancelled: 'Cancelada',
    },
  };
  return statuses[lang][status] || status;
};
export const accessibilityCopy = {
  en: {
    language: 'Language',
    menu: 'Menu',
    clearSearch: 'Clear search',
    closeFilters: 'Close filters',
    inventoryPages: 'Inventory pages',
    previousPage: 'Previous page',
    nextPage: 'Next page',
    remove: 'Remove',
    previousPhoto: 'Previous photo',
    nextPhoto: 'Next photo',
    heroAlt: 'Customers viewing an SUV at a Central African car market',
    playHero: 'Play hero video',
    pauseHero: 'Pause hero video',
  },
  fr: {
    language: 'Langue',
    menu: 'Menu',
    clearSearch: 'Effacer la recherche',
    closeFilters: 'Fermer les filtres',
    inventoryPages: 'Pages des annonces',
    previousPage: 'Page précédente',
    nextPage: 'Page suivante',
    remove: 'Retirer',
    previousPhoto: 'Photo précédente',
    nextPhoto: 'Photo suivante',
    heroAlt:
      'Des clients regardent un SUV sur un marché automobile d’Afrique centrale',
    playHero: 'Lire la vidéo d’accueil',
    pauseHero: 'Mettre la vidéo d’accueil en pause',
  },
  es: {
    language: 'Idioma',
    menu: 'Menú',
    clearSearch: 'Borrar búsqueda',
    closeFilters: 'Cerrar filtros',
    inventoryPages: 'Páginas de anuncios',
    previousPage: 'Página anterior',
    nextPage: 'Página siguiente',
    remove: 'Quitar',
    previousPhoto: 'Foto anterior',
    nextPhoto: 'Foto siguiente',
    heroAlt:
      'Clientes observando un SUV en un mercado de automóviles de África Central',
    playHero: 'Reproducir el vídeo de portada',
    pauseHero: 'Pausar el vídeo de portada',
  },
} as const;
export const formValue = (data: FormData, key: string, fallback = '') => {
  const value = data.get(key);
  return typeof value === 'string' && value ? value : fallback;
};
export const formImages = (data: FormData, main: string) =>
  Array.from(
    new Set([
      main,
      ...formValue(data, 'images')
        .split(/[\n,]/)
        .map((value) => value.trim())
        .filter(Boolean),
    ]),
  ).slice(0, 8);
export const ui = {
  en: {
    buyCar: 'Buy a car',
    rentCar: 'Rent a car',
    parts: 'Car parts',
    cart: 'Cart',
    signIn: 'Sign in',
    buy: 'Buy',
    rent: 'Rent',
    partsDemand: 'Parts on demand',
    allMakes: 'All makes',
    allModels: 'All {brand} models',
    models: 'Models',
    refine: 'Quick refine',
    clear: 'Clear all',
    selected: 'Selected filters',
    insurance: 'Rental terms available',
    options: 'Confirm dates with seller',
    added: 'Added',
    inCart: 'In cart',
    book: 'Request rental',
    addCart: 'Add to cart',
    details: 'View details',
    overview: 'Overview',
    equipment: 'Equipment',
    seller: 'Seller information',
    contact: 'Contact seller',
    inspected: 'Listing details reviewed',
    noAccident: 'Accident history: ask seller',
    original: 'Parts condition: ask seller',
    service: 'Service records available on request',
    close: 'Close details',
  },
  fr: {
    buyCar: 'Acheter une voiture',
    rentCar: 'Louer une voiture',
    parts: 'Pièces auto',
    cart: 'Panier',
    signIn: 'Se connecter',
    buy: 'Acheter',
    rent: 'Louer',
    partsDemand: 'Pièces sur demande',
    allMakes: 'Toutes les marques',
    allModels: 'Tous les modèles {brand}',
    models: 'Modèles',
    refine: 'Affiner',
    clear: 'Tout effacer',
    selected: 'Filtres sélectionnés',
    insurance: 'Conditions de location disponibles',
    options: 'Confirmer les dates avec le vendeur',
    added: 'Ajouté',
    inCart: 'Dans le panier',
    book: 'Demander la location',
    addCart: 'Ajouter au panier',
    details: 'Voir les détails',
    overview: 'Aperçu',
    equipment: 'Équipements',
    seller: 'Informations vendeur',
    contact: 'Contacter le vendeur',
    inspected: 'Informations de l’annonce vérifiées',
    noAccident: 'Accidents : demander au vendeur',
    original: 'État des pièces : demander au vendeur',
    service: 'Carnet d’entretien sur demande',
    close: 'Fermer les détails',
  },
  es: {
    buyCar: 'Comprar un coche',
    rentCar: 'Alquilar un coche',
    parts: 'Repuestos',
    cart: 'Carrito',
    signIn: 'Iniciar sesión',
    buy: 'Comprar',
    rent: 'Alquilar',
    partsDemand: 'Repuestos bajo pedido',
    allMakes: 'Todas las marcas',
    allModels: 'Todos los modelos {brand}',
    models: 'Modelos',
    refine: 'Afinar',
    clear: 'Borrar todo',
    selected: 'Filtros seleccionados',
    insurance: 'Condiciones de alquiler disponibles',
    options: 'Confirma las fechas con el vendedor',
    added: 'Añadido',
    inCart: 'En el carrito',
    book: 'Solicitar alquiler',
    addCart: 'Añadir al carrito',
    details: 'Ver detalles',
    overview: 'Resumen',
    equipment: 'Equipamiento',
    seller: 'Información del vendedor',
    contact: 'Contactar al vendedor',
    inspected: 'Detalles del anuncio revisados',
    noAccident: 'Accidentes: consultar al vendedor',
    original: 'Estado de piezas: consultar al vendedor',
    service: 'Historial de mantenimiento bajo pedido',
    close: 'Cerrar detalles',
  },
} as const;
export const marketCopy = {
  en: {
    trust: [
      'Five regional markets',
      'Clear listing details',
      'Direct seller contact',
      'Parts on demand',
    ],
    browse: 'Browse makes',
    listings: 'listings',
    allBrands: 'All brands',
    locationGroup: 'Location & source',
    essentialsGroup: 'Price & essentials',
    specificationsGroup: 'More specifications',
    year: 'Year from',
    location: 'Location',
    source: 'Stock source',
    local: 'Local stock',
    abroad: 'Abroad stock',
    country: 'Country',
    importRegion: 'Import region',
    engine: 'Engine size',
    sellerType: 'Seller type',
    minPrice: 'Minimum FCFA',
    maxPrice: 'Maximum FCFA',
    dailyPrice: 'Daily rate',
    rentUnder: 'Under 60,000 FCFA/day',
    verifiedOnly: 'Verified listing',
    availableOnly: 'Available listing',
    onDemand: 'On demand',
    listedToday: 'Listed today',
    dayAgo: 'day ago',
    daysAgo: 'days ago',
    latestOnly: 'Listed in 7 days',
    privateOnly: 'Private seller',
    mileage: 'Mileage',
    transmission: 'Transmission',
    drivetrain: 'Drivetrain',
    color: 'Color',
    doors: 'Doors',
    seats: 'Seats',
    under: 'Under',
    doorCount: 'doors',
    seatCount: 'seats',
    localAvailability: 'Available locally',
    abroadAvailability: 'Available abroad — import required',
    importNote:
      'Estimated import: 4–8 weeks. Shipping and customs are quoted separately.',
    show: 'Show',
    cars: 'cars',
    rentReady: 'AVAILABLE TO RENT',
    trip: 'cars ready for your trip',
    sort: [
      'Price: Low to high',
      'Price: High to low',
      'Newest first',
      'Oldest first',
      'Lowest mileage',
      'Engine size',
    ],
    rentalTerms: 'Rental terms shown',
    selected: 'selected',
    compareNow: 'Compare now',
    help: 'Help',
    privacy: 'Privacy',
    terms: 'Terms',
    tagline: 'Move happy.',
  },
  fr: {
    trust: [
      'Cinq marchés régionaux',
      'Annonces détaillées',
      'Contact direct vendeur',
      'Pièces sur demande',
    ],
    browse: 'Parcourir les marques',
    listings: 'annonces',
    allBrands: 'Toutes les marques',
    locationGroup: 'Localisation et origine',
    essentialsGroup: 'Prix et critères essentiels',
    specificationsGroup: 'Plus de caractéristiques',
    year: 'Année à partir de',
    location: 'Localisation',
    source: 'Origine du stock',
    local: 'Stock local',
    abroad: 'Stock à l’étranger',
    country: 'Pays',
    importRegion: 'Région d’importation',
    engine: 'Cylindrée',
    sellerType: 'Type de vendeur',
    minPrice: 'Minimum FCFA',
    maxPrice: 'Maximum FCFA',
    dailyPrice: 'Tarif journalier',
    rentUnder: 'Moins de 60 000 FCFA/jour',
    verifiedOnly: 'Annonce vérifiée',
    availableOnly: 'Annonce disponible',
    onDemand: 'Sur demande',
    listedToday: 'Publiée aujourd’hui',
    dayAgo: 'jour',
    daysAgo: 'jours',
    latestOnly: 'Publiée sous 7 jours',
    privateOnly: 'Vendeur particulier',
    mileage: 'Kilométrage',
    transmission: 'Transmission',
    drivetrain: 'Motricité',
    color: 'Couleur',
    doors: 'Portes',
    seats: 'Places',
    under: 'Moins de',
    doorCount: 'portes',
    seatCount: 'places',
    localAvailability: 'Disponible localement',
    abroadAvailability: 'À l’étranger — importation requise',
    importNote:
      'Importation estimée : 4 à 8 semaines. Transport et douane sont chiffrés séparément.',
    show: 'Voir',
    cars: 'voitures',
    rentReady: 'DISPONIBLES À LA LOCATION',
    trip: 'voitures prêtes pour votre voyage',
    sort: [
      'Prix croissant',
      'Prix décroissant',
      'Plus récentes',
      'Plus anciennes',
      'Kilométrage le plus bas',
      'Cylindrée',
    ],
    rentalTerms: 'Conditions de location',
    selected: 'sélectionnées',
    compareNow: 'Comparer maintenant',
    help: 'Aide',
    privacy: 'Confidentialité',
    terms: 'Conditions',
    tagline: 'Roulez heureux.',
  },
  es: {
    trust: [
      'Cinco mercados regionales',
      'Anuncios detallados',
      'Contacto directo',
      'Repuestos bajo pedido',
    ],
    browse: 'Explorar marcas',
    listings: 'anuncios',
    allBrands: 'Todas las marcas',
    locationGroup: 'Ubicación y origen',
    essentialsGroup: 'Precio y datos esenciales',
    specificationsGroup: 'Más características',
    year: 'Año desde',
    location: 'Ubicación',
    source: 'Origen del stock',
    local: 'Stock local',
    abroad: 'Stock en el extranjero',
    country: 'País',
    importRegion: 'Región de importación',
    engine: 'Cilindrada',
    sellerType: 'Tipo de vendedor',
    minPrice: 'Mínimo FCFA',
    maxPrice: 'Máximo FCFA',
    dailyPrice: 'Tarifa diaria',
    rentUnder: 'Menos de 60.000 FCFA/día',
    verifiedOnly: 'Anuncio verificado',
    availableOnly: 'Anuncio disponible',
    onDemand: 'Bajo pedido',
    listedToday: 'Publicado hoy',
    dayAgo: 'día',
    daysAgo: 'días',
    latestOnly: 'Publicado en 7 días',
    privateOnly: 'Vendedor particular',
    mileage: 'Kilometraje',
    transmission: 'Transmisión',
    drivetrain: 'Tracción',
    color: 'Color',
    doors: 'Puertas',
    seats: 'Plazas',
    under: 'Menos de',
    doorCount: 'puertas',
    seatCount: 'plazas',
    localAvailability: 'Disponible localmente',
    abroadAvailability: 'En el extranjero — requiere importación',
    importNote:
      'Importación estimada: 4–8 semanas. Envío y aduanas se cotizan por separado.',
    show: 'Ver',
    cars: 'coches',
    rentReady: 'DISPONIBLES PARA ALQUILAR',
    trip: 'coches listos para tu viaje',
    sort: [
      'Precio: menor a mayor',
      'Precio: mayor a menor',
      'Más recientes',
      'Más antiguos',
      'Menor kilometraje',
      'Cilindrada',
    ],
    rentalTerms: 'Condiciones del alquiler',
    selected: 'seleccionados',
    compareNow: 'Comparar ahora',
    help: 'Ayuda',
    privacy: 'Privacidad',
    terms: 'Condiciones',
    tagline: 'Conduce feliz.',
  },
} as const;
export const footerCopy = {
  en: {
    summary: 'Buy, rent and request car parts across Central Africa.',
    markets:
      'Our five markets: Republic of the Congo, Cameroon, Gabon, Angola (Cabinda) and DR Congo.',
    explore: 'Explore',
    buy: 'Buy a car',
    rent: 'Rent a car',
    parts: 'Request a part',
    gallery: 'Shipments',
    about: 'About us',
    contact: 'Contact us',
    accountHelp: 'Account & help',
    account: 'My account',
    cartRequests: 'Cart & requests',
    help: 'Help',
    legal: 'Legal',
    privacy: 'Privacy',
    terms: 'Marketplace terms',
    notice:
      'Purchase and rental requests require seller confirmation. JFcars does not process payments on this website; payment is arranged directly with the seller. JFcars does not issue refunds.',
    copyright: 'All rights reserved.',
  },
  fr: {
    summary: 'Achetez, louez et demandez des pièces auto en Afrique centrale.',
    markets:
      'Nos cinq marchés : République du Congo, Cameroun, Gabon, Angola (Cabinda) et RD Congo.',
    explore: 'Découvrir',
    buy: 'Acheter une voiture',
    rent: 'Louer une voiture',
    parts: 'Demander une pièce',
    gallery: 'Expéditions',
    about: 'À propos',
    contact: 'Nous contacter',
    accountHelp: 'Compte et assistance',
    account: 'Mon compte',
    cartRequests: 'Panier et demandes',
    help: 'Aide',
    legal: 'Informations légales',
    privacy: 'Confidentialité',
    terms: 'Conditions de la place de marché',
    notice:
      'Les demandes d’achat et de location nécessitent la confirmation du vendeur. JFcars ne traite aucun paiement sur ce site ; le paiement est organisé directement avec le vendeur. JFcars n’effectue aucun remboursement.',
    copyright: 'Tous droits réservés.',
  },
  es: {
    summary: 'Compra, alquila y solicita repuestos en África Central.',
    markets:
      'Nuestros cinco mercados: República del Congo, Camerún, Gabón, Angola (Cabinda) y RD del Congo.',
    explore: 'Explorar',
    buy: 'Comprar un coche',
    rent: 'Alquilar un coche',
    parts: 'Solicitar un repuesto',
    gallery: 'Envíos',
    about: 'Quiénes somos',
    contact: 'Contáctanos',
    accountHelp: 'Cuenta y ayuda',
    account: 'Mi cuenta',
    cartRequests: 'Carrito y solicitudes',
    help: 'Ayuda',
    legal: 'Legal',
    privacy: 'Privacidad',
    terms: 'Condiciones del mercado',
    notice:
      'Las solicitudes de compra y alquiler requieren la confirmación del vendedor. JFcars no procesa pagos en este sitio; el pago se organiza directamente con el vendedor. JFcars no realiza reembolsos.',
    copyright: 'Todos los derechos reservados.',
  },
} as const;
export const flowCopy = {
  en: {
    eyebrow: 'Central Africa’s trusted car market.',
    markets: 'regional markets',
    quick: ['Electric', 'SUV', 'Under 20M FCFA'],
    sellEyebrow: 'SELL WITH JFCARS',
    account: 'YOUR JFCARS ACCOUNT',
    welcome: 'Welcome back.',
    moving: 'Let’s get you moving.',
    signinDesc: 'Sign in to manage your cars, bookings and requests.',
    signupDesc: 'Create an account to save, compare and move faster.',
    signIn: 'Sign in',
    create: 'Create account',
    name: 'Full name',
    email: 'Email address',
    password: 'Password',
    remember: 'Remember me',
    forgot: 'Forgot password?',
    forgotSent: 'Reset instructions are ready for the email entered above.',
    continue: 'By continuing, you agree to our Terms and Privacy Policy.',
    selection: 'YOUR SELECTION',
    estimated: 'Estimated total',
    purchase: 'Purchase',
    rental: 'Rental',
    day: 'day',
    rentalDates: 'Rental dates',
    rentalStart: 'Pickup date',
    rentalEnd: 'Return date',
    pickupAt: 'Pickup',
    rentalConsent:
      'I understand this is an availability request. The seller confirms the deposit, ID and licence requirements, and final rental terms before payment.',
    rentalRequired:
      'Choose valid pickup and return dates, then confirm the rental terms.',
    chooseDates: 'Choose dates to calculate the rental total',
    checkout: 'Submit purchase or rental request',
    checkoutNote:
      'JFcars takes no payment on this website. Payment is arranged separately with the seller. JFcars does not issue refunds.',
    signinContinue: 'Sign in to continue',
    checkoutDone:
      'Request submitted. No purchase or rental is confirmed until the seller accepts it and agrees the final terms with you.',
    emptyCart: 'Your cart is ready for an adventure.',
    emptyCartP: 'Add a car or rental and it will appear here.',
    browse: 'Keep browsing',
    profileSaved: 'Profile changes saved.',
    viewDetails: 'View details',
    adminHint: 'Admin access is limited to the verified JFcars owner.',
    helpTitle: 'How can we help?',
    aboutTitle: 'About JFcars',
    contactTitle: 'Contact us',
    privacyTitle: 'Privacy at JFcars',
    termsTitle: 'Marketplace terms',
    helpText:
      'Browse, compare, rent or request a part. For transaction support, use the seller form on any listing.',
    aboutText:
      'JFcars connects buyers and renters with vehicles, parts and shipment updates across our Central African markets. We focus on clear information, local support and visible logistics from departure to arrival.',
    contactText:
      'Tell our team how we can help. For a specific vehicle, include its make or listing name in your message.',
    contactName: 'Your name',
    contactWay: 'Phone, WhatsApp or email',
    contactMessage: 'How can we help?',
    contactSend: 'Send message',
    contactSent: 'Thank you. Your message has been sent to the JFcars team.',
    contactError: 'Your message could not be sent. Please try again.',
    privacyText:
      'Marketplace requests and signed-in profile details—including contact, location and language preferences—are stored securely for service delivery. Device preferences may also be stored locally.',
    termsText:
      'All requests remain subject to inspection, seller confirmation, payment, delivery and local registration requirements. JFcars does not issue refunds.',
    sellTitle: 'List your vehicle',
    sellText:
      'Share the essentials. The JFcars team will review your listing before it goes live.',
    sellDone:
      'Listing request saved. Our team will contact you for photos and verification.',
  },
  fr: {
    eyebrow: 'Le marché automobile de confiance en Afrique centrale.',
    markets: 'marchés régionaux',
    quick: ['Électrique', 'SUV', 'Moins de 20 M FCFA'],
    sellEyebrow: 'VENDEZ AVEC JFCARS',
    account: 'VOTRE COMPTE JFCARS',
    welcome: 'Bon retour.',
    moving: 'Prenons la route.',
    signinDesc:
      'Connectez-vous pour gérer vos voitures, réservations et demandes.',
    signupDesc:
      'Créez un compte pour enregistrer, comparer et avancer plus vite.',
    signIn: 'Se connecter',
    create: 'Créer un compte',
    name: 'Nom complet',
    email: 'Adresse e-mail',
    password: 'Mot de passe',
    remember: 'Se souvenir de moi',
    forgot: 'Mot de passe oublié ?',
    forgotSent:
      'Les instructions seront envoyées à l’adresse saisie ci-dessus.',
    continue:
      'En continuant, vous acceptez nos Conditions et notre Politique de confidentialité.',
    selection: 'VOTRE SÉLECTION',
    estimated: 'Total estimé',
    purchase: 'Achat',
    rental: 'Location',
    day: 'jour',
    rentalDates: 'Dates de location',
    rentalStart: 'Date de prise en charge',
    rentalEnd: 'Date de retour',
    pickupAt: 'Prise en charge',
    rentalConsent:
      'Je comprends qu’il s’agit d’une demande de disponibilité. Le vendeur confirme la caution, les exigences de pièce d’identité et de permis, ainsi que les conditions finales avant le paiement.',
    rentalRequired:
      'Choisissez des dates valides, puis confirmez les conditions de location.',
    chooseDates: 'Choisissez les dates pour calculer le total de la location',
    checkout: 'Envoyer la demande d’achat ou de location',
    checkoutNote:
      'JFcars ne prélève aucun paiement sur ce site. Le paiement est organisé séparément avec le vendeur. JFcars n’effectue aucun remboursement.',
    signinContinue: 'Se connecter pour continuer',
    checkoutDone:
      'Demande envoyée. Aucun achat ni aucune location n’est confirmé tant que le vendeur ne l’a pas accepté et n’a pas convenu des conditions finales avec vous.',
    emptyCart: 'Votre panier attend votre prochaine aventure.',
    emptyCartP: 'Ajoutez une voiture ou une location : elle apparaîtra ici.',
    browse: 'Continuer à chercher',
    profileSaved: 'Profil enregistré.',
    viewDetails: 'Voir les détails',
    adminHint: 'L’accès Admin est réservé au propriétaire JFcars vérifié.',
    helpTitle: 'Comment pouvons-nous aider ?',
    aboutTitle: 'À propos de JFcars',
    contactTitle: 'Nous contacter',
    privacyTitle: 'Confidentialité chez JFcars',
    termsTitle: 'Conditions de la place de marché',
    helpText:
      'Parcourez, comparez, louez ou demandez une pièce. Pour une transaction, utilisez le formulaire vendeur de l’annonce.',
    aboutText:
      'JFcars met en relation les acheteurs et les locataires avec des véhicules, des pièces et le suivi des expéditions sur nos marchés d’Afrique centrale. Nous privilégions des informations claires, un accompagnement local et une logistique visible du départ à l’arrivée.',
    contactText:
      'Expliquez à notre équipe comment nous pouvons vous aider. Pour un véhicule précis, indiquez sa marque ou le nom de l’annonce.',
    contactName: 'Votre nom',
    contactWay: 'Téléphone, WhatsApp ou e-mail',
    contactMessage: 'Comment pouvons-nous vous aider ?',
    contactSend: 'Envoyer le message',
    contactSent: 'Merci. Votre message a été envoyé à l’équipe JFcars.',
    contactError: 'Votre message n’a pas pu être envoyé. Réessayez.',
    privacyText:
      'Les demandes et les informations du profil connecté—notamment le contact, la localisation et la langue—sont conservées pour assurer le service. Certaines préférences peuvent aussi être stockées sur cet appareil.',
    termsText:
      'Toute demande reste soumise à l’inspection, à la confirmation du vendeur, au paiement, à la livraison et aux règles locales d’immatriculation. JFcars n’effectue aucun remboursement.',
    sellTitle: 'Publier votre véhicule',
    sellText:
      'Partagez l’essentiel. L’équipe JFcars vérifiera votre annonce avant publication.',
    sellDone:
      'Demande enregistrée. Notre équipe vous contactera pour les photos et la vérification.',
  },
  es: {
    eyebrow: 'El mercado de automóviles de confianza en África Central.',
    markets: 'mercados regionales',
    quick: ['Eléctrico', 'SUV', 'Menos de 20 M FCFA'],
    sellEyebrow: 'VENDE CON JFCARS',
    account: 'TU CUENTA JFCARS',
    welcome: 'Bienvenido de nuevo.',
    moving: 'Pongámonos en marcha.',
    signinDesc: 'Inicia sesión para gestionar coches, reservas y solicitudes.',
    signupDesc: 'Crea una cuenta para guardar, comparar y avanzar más rápido.',
    signIn: 'Iniciar sesión',
    create: 'Crear cuenta',
    name: 'Nombre completo',
    email: 'Correo electrónico',
    password: 'Contraseña',
    remember: 'Recordarme',
    forgot: '¿Olvidaste la contraseña?',
    forgotSent: 'Las instrucciones se enviarán al correo indicado arriba.',
    continue:
      'Al continuar, aceptas nuestros Términos y Política de privacidad.',
    selection: 'TU SELECCIÓN',
    estimated: 'Total estimado',
    purchase: 'Compra',
    rental: 'Alquiler',
    day: 'día',
    rentalDates: 'Fechas de alquiler',
    rentalStart: 'Fecha de recogida',
    rentalEnd: 'Fecha de devolución',
    pickupAt: 'Recogida',
    rentalConsent:
      'Entiendo que es una solicitud de disponibilidad. El vendedor confirma el depósito, los requisitos de identidad y permiso, y las condiciones finales antes del pago.',
    rentalRequired:
      'Elige fechas válidas y confirma las condiciones del alquiler.',
    chooseDates: 'Elige las fechas para calcular el total del alquiler',
    checkout: 'Enviar solicitud de compra o alquiler',
    checkoutNote:
      'JFcars no cobra pagos en este sitio. El pago se organiza por separado con el vendedor. JFcars no realiza reembolsos.',
    signinContinue: 'Inicia sesión para continuar',
    checkoutDone:
      'Solicitud enviada. La compra o el alquiler no se confirma hasta que el vendedor lo acepte y acuerde contigo las condiciones finales.',
    emptyCart: 'Tu carrito espera una aventura.',
    emptyCartP: 'Añade un coche o alquiler y aparecerá aquí.',
    browse: 'Seguir buscando',
    profileSaved: 'Perfil guardado.',
    viewDetails: 'Ver detalles',
    adminHint:
      'El acceso Admin está limitado al propietario verificado de JFcars.',
    helpTitle: '¿Cómo podemos ayudarte?',
    aboutTitle: 'Quiénes somos',
    contactTitle: 'Contáctanos',
    privacyTitle: 'Privacidad en JFcars',
    termsTitle: 'Términos del mercado',
    helpText:
      'Explora, compara, alquila o solicita una pieza. Para una operación, usa el formulario del vendedor en el anuncio.',
    aboutText:
      'JFcars conecta a compradores y arrendatarios con vehículos, repuestos y el seguimiento de envíos en nuestros mercados de África Central. Priorizamos la información clara, la asistencia local y una logística visible desde la salida hasta la llegada.',
    contactText:
      'Cuéntale a nuestro equipo cómo podemos ayudarte. Para un vehículo concreto, incluye la marca o el nombre del anuncio.',
    contactName: 'Tu nombre',
    contactWay: 'Teléfono, WhatsApp o correo',
    contactMessage: '¿Cómo podemos ayudarte?',
    contactSend: 'Enviar mensaje',
    contactSent: 'Gracias. Tu mensaje ha sido enviado al equipo de JFcars.',
    contactError: 'No se pudo enviar el mensaje. Inténtalo de nuevo.',
    privacyText:
      'Las solicitudes y los datos del perfil conectado—incluidos contacto, ubicación e idioma—se guardan para prestar el servicio. Algunas preferencias también pueden guardarse en este dispositivo.',
    termsText:
      'Toda solicitud está sujeta a inspección, confirmación del vendedor, pago, entrega y requisitos locales de matriculación. JFcars no realiza reembolsos.',
    sellTitle: 'Publica tu vehículo',
    sellText:
      'Comparte lo esencial. El equipo de JFcars revisará el anuncio antes de publicarlo.',
    sellDone:
      'Solicitud guardada. Nuestro equipo te contactará para las fotos y la verificación.',
  },
} as const;
export const profileCopy = {
  en: {
    welcome: 'Welcome back',
    tabs: ['Overview', 'Purchases', 'Rentals', 'Settings'],
    glance: 'Your JFcars at a glance',
    saved: 'Saved cars',
    cart: 'In cart',
    parts: 'Part requests',
    recent: 'Recent activity',
    completion: 'Profile completeness',
    complete: 'Profile complete',
    completeText: 'Your contact and market preferences are ready to use.',
    incompleteText: 'Add your missing details for faster requests and replies.',
    completeAction: 'Complete profile',
    details: 'Your details',
    notProvided: 'Not provided',
    noPurchases: 'No purchases yet',
    purchasesText: 'Your vehicle orders will be tracked here.',
    noRentals: 'No upcoming rentals',
    rentalsText: 'Book a car and manage your trip here.',
    settings: 'Profile settings',
    settingsText:
      'Keep the details our regional team and sellers use to contact you up to date.',
    phone: 'Phone or WhatsApp number',
    country: 'Country or market',
    city: 'City',
    preferredLanguage: 'Preferred language',
    preferredContact: 'Preferred contact method',
    chooseCountry: 'Choose your market',
    emailManaged: 'Verified and managed by your ChatGPT sign-in.',
    authNote:
      'Secure sign-in provides your verified email. Add your phone, city and preferences from your profile.',
    save: 'Save changes',
    saving: 'Saving…',
    saveError: 'Your profile could not be saved. Please try again.',
    signout: 'Sign out',
  },
  fr: {
    welcome: 'Bon retour',
    tabs: ['Aperçu', 'Achats', 'Locations', 'Paramètres'],
    glance: 'Votre activité JFcars',
    saved: 'Voitures favorites',
    cart: 'Dans le panier',
    parts: 'Demandes de pièces',
    recent: 'Activité récente',
    completion: 'Progression du profil',
    complete: 'Profil complet',
    completeText:
      'Vos coordonnées et préférences sont prêtes à être utilisées.',
    incompleteText:
      'Ajoutez les informations manquantes pour accélérer vos demandes et réponses.',
    completeAction: 'Compléter le profil',
    details: 'Vos informations',
    notProvided: 'Non renseigné',
    noPurchases: 'Aucun achat',
    purchasesText: 'Vos commandes de véhicules seront suivies ici.',
    noRentals: 'Aucune location à venir',
    rentalsText: 'Réservez une voiture et gérez votre voyage ici.',
    settings: 'Paramètres du profil',
    settingsText:
      'Tenez à jour les informations utilisées par notre équipe régionale et les vendeurs pour vous contacter.',
    phone: 'Téléphone ou WhatsApp',
    country: 'Pays ou marché',
    city: 'Ville',
    preferredLanguage: 'Langue préférée',
    preferredContact: 'Moyen de contact préféré',
    chooseCountry: 'Choisissez votre marché',
    emailManaged: 'Adresse vérifiée et gérée par votre connexion ChatGPT.',
    authNote:
      'La connexion sécurisée fournit votre e-mail vérifié. Ajoutez votre téléphone, votre ville et vos préférences dans votre profil.',
    save: 'Enregistrer',
    saving: 'Enregistrement…',
    saveError: 'Impossible d’enregistrer votre profil. Réessayez.',
    signout: 'Se déconnecter',
  },
  es: {
    welcome: 'Te damos la bienvenida',
    tabs: ['Resumen', 'Compras', 'Alquileres', 'Ajustes'],
    glance: 'Tu actividad en JFcars',
    saved: 'Coches guardados',
    cart: 'En el carrito',
    parts: 'Solicitudes de piezas',
    recent: 'Actividad reciente',
    completion: 'Progreso del perfil',
    complete: 'Perfil completo',
    completeText: 'Tus datos de contacto y preferencias están listos.',
    incompleteText:
      'Añade los datos que faltan para agilizar tus solicitudes y respuestas.',
    completeAction: 'Completar perfil',
    details: 'Tus datos',
    notProvided: 'Sin indicar',
    noPurchases: 'Sin compras todavía',
    purchasesText: 'Aquí podrás seguir tus pedidos de vehículos.',
    noRentals: 'Sin alquileres próximos',
    rentalsText: 'Reserva un coche y gestiona tu viaje aquí.',
    settings: 'Ajustes del perfil',
    settingsText:
      'Mantén actualizados los datos que nuestro equipo regional y los vendedores usan para contactarte.',
    phone: 'Teléfono o WhatsApp',
    country: 'País o mercado',
    city: 'Ciudad',
    preferredLanguage: 'Idioma preferido',
    preferredContact: 'Método de contacto preferido',
    chooseCountry: 'Elige tu mercado',
    emailManaged: 'Correo verificado y gestionado por tu acceso de ChatGPT.',
    authNote:
      'El acceso seguro proporciona tu correo verificado. Añade teléfono, ciudad y preferencias desde tu perfil.',
    save: 'Guardar cambios',
    saving: 'Guardando…',
    saveError: 'No se pudo guardar tu perfil. Inténtalo de nuevo.',
    signout: 'Cerrar sesión',
  },
} as const;
export const compareCopy = {
  en: {
    eyebrow: 'SIDE-BY-SIDE',
    title: 'Compare your shortlist',
    close: 'Close comparison',
    remove: 'Remove',
    mileage: 'Mileage',
    body: 'Body',
    transmission: 'Transmission',
    drivetrain: 'Drivetrain',
    seats: 'Seats',
    location: 'Location',
    add: 'Add to cart',
  },
  fr: {
    eyebrow: 'CÔTE À CÔTE',
    title: 'Comparez votre sélection',
    close: 'Fermer la comparaison',
    remove: 'Retirer',
    mileage: 'Kilométrage',
    body: 'Carrosserie',
    transmission: 'Transmission',
    drivetrain: 'Motricité',
    seats: 'Places',
    location: 'Localisation',
    add: 'Ajouter au panier',
  },
  es: {
    eyebrow: 'LADO A LADO',
    title: 'Compara tu selección',
    close: 'Cerrar comparación',
    remove: 'Quitar',
    mileage: 'Kilometraje',
    body: 'Carrocería',
    transmission: 'Transmisión',
    drivetrain: 'Tracción',
    seats: 'Plazas',
    location: 'Ubicación',
    add: 'Añadir al carrito',
  },
} as const;
